### ISSUE TITLE
problem about block weight.

### ISSUE THREAD

**Issue by seohyunbae** [kahypar/kahypar#104]
hello.
I'm using m1 Mac.
I followed your comments, so KaHyPar in /build/kahypar/application is work very well.
Then, I tired to using kahypar as c++ library.

I want to use block_weight, so I write the code like below.

#include <memory>
#include <vector>
#include <iostream>
#include <libkahypar.h>

int main(){

    kahypar_context_t* context = kahypar_context_new();
    kahypar_configure_context_from_file(context, "../kahypar/config/cut_rKaHyPar_sea20.ini");

    const kahypar_hypernode_id_t num_vertices = 7;
    const kahypar_hyperedge_id_t num_hyperedges = 4;

    std::unique_ptr<kahypar_hypernode_weight_t[]> hypernode_weights = std::make_unique<kahypar_hypernode_weight_t[]>(num_vertices);
    hypernode_weights[0] = 1;
    hypernode_weights[1] = 2;
    hypernode_weights[2] = 3;
    hypernode_weights[3] = 4;
    hypernode_weights[4] = 3;
    hypernode_weights[5] = 2;
    hypernode_weights[6] = 1;

    std::unique_ptr<size_t[]> hyperedge_indices = std::make_unique<size_t[]>(num_hyperedges + 1);
    hyperedge_indices[0] = 0;
    hyperedge_indices[1] = 2;
    hyperedge_indices[2] = 6;
    hyperedge_indices[3] = 9;
    hyperedge_indices[4] = 12;

    std::unique_ptr<kahypar_hyperedge_id_t[]> hyperedges = std::make_unique<kahypar_hyperedge_id_t[]>(num_hyperedges);

    hyperedges[0] = 0;  hyperedges[1] = 2;
    hyperedges[2] = 0;  hyperedges[3] = 1;
    hyperedges[4] = 3;  hyperedges[5] = 4;
    hyperedges[6] = 3;  hyperedges[7] = 4;
    hyperedges[8] = 6;  hyperedges[9] = 2;
    hyperedges[10] = 5; hyperedges[11] = 6;

    const double imbalance = 0.2;
    const kahypar_partition_id_t k = 2;

    std::unique_ptr<kahypar_hypernode_weight_t[]> block_weights = std::make_unique<kahypar_hypernode_weight_t[]>(k);
    block_weights[0] = 6;
    block_weights[1] = 10;

    kahypar_set_custom_target_block_weights(k, block_weights, context);

    kahypar_hyperedge_weight_t objective = 0;

    std::vector<kahypar_partition_id_t> partition(num_vertices, -1);

    kahypar_partition(num_vertices, num_hyperedges, imbalance, k, hypernode_weights.get(), nullptr, hyperedge_indices.get(), hyperedges.get(), &objective, context, partition.data());

    for(int i = 0; i != num_vertices; ++i){
        std::cout<< i << " : " << partition[i] << std::endl;
    }

    kahypar_context_free(context);

    return 0;
}

But, when I compile the main.cpp with g++, there is an error.

main.cpp:46:5: error: no matching function for call to 'kahypar_set_custom_target_block_weights'
    kahypar_set_custom_target_block_weights(k, block_weights, context);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/libkahypar.h:65:18: note: candidate function not viable: no known conversion from 'std::unique_ptr<kahypar_hypernode_weight_t []>' to 'const kahypar_hypernode_weight_t *' (aka 'const int *') for 2nd argument
KAHYPAR_API void kahypar_set_custom_target_block_weights(const kahypar_partition_id_t num_blocks,
                 ^
1 error generated.

I tired to repair that code, but I can't
(using reinterpret_cast and new-delete are all failed)

So I wonder how can I add the block_weight in the main.cpp and what is the problem about my code.

+) there is one more error below, when I execute compiled program without block_weights. How can I fix it?
(the error was not always being. sometimes, program run well. but the other times, there is error(error 1 or error 2))

error 1)
program(27277,0x1040d8580) malloc: Heap corruption detected, free list is damaged at 0x600001c04310
*** Incorrect guard value: 8589934598
program(27277,0x1040d8580) malloc: *** set a breakpoint in malloc_error_break to debug

error2)
zsh: segmentation fault  ./program

Thank you for your efforts.

**Comment by seohyunbae** [comment]
I work it out!
Solution is that install boots with all program_options.
(sudo ./bootstrap.sh --with-libraries=all).

**Comment by SebastianSchlag** [comment]
Hi,

my guess is that 

```
kahypar_set_custom_target_block_weights(k, block_weights, context);
```

should have been

```
kahypar_set_custom_target_block_weights(k, *block_weights, context);
```

 since the function expects the second parameter to be of type `kahypar_hypernode_weight_t*` and not of type `std::unique_ptr<kahypar_hypernode_weight_t []>` (see: https://github.com/kahypar/kahypar/blob/9a2179fdbf396dc1806a407c5590a51794b8a538/include/libkahypar.h#L65-L67)

You can find an example of how to use custom block weights in this interface test: https://github.com/kahypar/kahypar/blob/9a2179fdbf396dc1806a407c5590a51794b8a538/tests/interface/interface_test.cc#L426-L431

The segfault you get when you try to run your example without custom block weights seems to indicate that you set up the hypergraph data structure incorrectly. This test case:https://github.com/kahypar/kahypar/blob/9a2179fdbf396dc1806a407c5590a51794b8a538/tests/interface/interface_test.cc#L372 should be very similar to what you are trying to do. Could you try running that code?

**Comment by seohyunbae** [comment]
I can fix my code with your advice!
thank you for your effort!

**Comment by SebastianSchlag** [comment]
That's great! 👍
