### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by nina23bom** [kahypar/kahypar#106]
macOS 10.15.6

installed the precompiled version use:
python3 -m pip install --index-url https://pypi.org/simple/ --no-deps kahypar

get message:
Looking in indexes: https://pypi.org/simple/
Requirement already satisfied: kahypar in /opt/anaconda3/lib/python3.8/site-packages (1.1.5)

But while import kahypar in Jupyter notebook:
import kahypar as kahypar

Got the following Import Error:

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-08c09dcdac73> in <module>
      1 import os
----> 2 import kahypar as kahypar

ImportError: dlopen(/opt/anaconda3/lib/python3.8/site-packages/kahypar.cpython-38-darwin.so, 2): Library not loaded: /usr/local/opt/boost/lib/libboost_program_options-mt.dylib
  Referenced from: /opt/anaconda3/lib/python3.8/site-packages/kahypar.cpython-38-darwin.so
  Reason: image not found

Any help is appreciated!

**Comment by SebastianSchlag** [comment]
Hi @nina23bom,

Thanks for reaching out.

That's odd. It seems like somehow the macOS wheel builds behave differently than the linux builds.
I've compiled a bunch of updated wheels for macOS. Could you try to install one of those (e.g. via `pip3 install kahypar==1.1.7`)?

If that fails as well, please let me know. Another approach that could work is: https://github.com/kahypar/kahypar/pull/102

**Comment by nina23bom** [comment]
> 
Thanks! It works now!

**Comment by SebastianSchlag** [comment]
Awesome! Thanks for confirming. Just to be sure: Did installing version `1.1.7` via pip work for you or did you have to resort to one of the alternative approaches?

My current assumption is that `cibuildwheel`, which we use to create macOS wheels (see[ build_macos_locally.sh](https://github.com/kahypar/kahypar/blob/master/scripts/python_wheels/build_macos_locally.sh)), doesn't handle the boost dependency properly. The new wheels that I build yesterday don't rely on a system-wide boost installation but instead use the `KAHYPAR_USE_MINIMAL_BOOST` option to download and compile a custom boost binary.

**Comment by nina23bom** [comment]
I reinstalled using 

pip3 install kahypar==1.1.7

 and it worked beautifully.

**Comment by SebastianSchlag** [comment]
That's great news. Thanks for confirming!
