### ISSUE TITLE
Stuck during coarsening

### ISSUE THREAD

**Issue by Coloquinte** [kahypar/kahypar#107]
I have an hypergraph (adaptec1 benchmark, a VLSI circuit, ~200k nodes/edges) that seems to get stuck at the coarsening phase (left it to compute overnight once).

[adaptec1.hgr.gz](https://github.com/kahypar/kahypar/files/8507233/adaptec1.hgr.gz)

`./KaHyPar -h adaptec1.hgr -k 2 -e 0.03 -o cut -m direct -p ../../../config/cut_kKaHyPar_sea20.ini -v1`

I don't think the graph has anything pathological. I removed large edges to no avail. There are probably unconnected nodes.

Is there a particular option/method I should try ?

Thanks!

**Comment by SebastianSchlag** [comment]
Hey @Coloquinte, thanks for reaching out.
 It looks like your input hypergraph is broken / violates a key assumption made by KaHyPar: We assume hyperedges to be sets rather than multisets, i.e., a vertex can only be contained in a hyperedge _once_.

Looking at your instance, there seem to be multiple hyperedges that contain the same vertex multiple times, e.g. line 212687: 
`149101 147219 147140 147140 147129 147129 147107 147107 147020 147009 147009 146973 146951 146951 146853 146852`.

**Comment by SebastianSchlag** [comment]
https://github.com/kahypar/kahypar/pull/108 will make sure that we output an error message in the future if a hyperedge contains a pin more than once.

**Comment by SebastianSchlag** [comment]
Actually, after briefly discussing with @kittobi1992, we decided to change the implementation to issue a warning and to remove any duplicated pins during parsing.

**Comment by Coloquinte** [comment]
Thanks for looking into this so quickly!

It would be nice to have the same check when using the APIs - maybe just making it an error, as I am not sure if there would be any side effect in skipping it [in the constructor](https://github.com/kahypar/kahypar/blob/3802b7976002663b4126a11c5bff84996a830fb9/kahypar/datastructure/hypergraph.h#L640).
If you're OK with the principle I can make a pull request.

**Comment by SebastianSchlag** [comment]
The new check is included in the API as well if you read in a hypergraph from a file as the C API uses the same function under the hood. But you are right, if the hypergraph is created by the caller and then passed in through `kahypar_create_hypergraph`, this is not yet fixed.

You are right in that just skipping duplicate pins in the constructor would mess things up. The quick and dirty fix would probably be to implement a `kahypar::io::sanitizeHypergraph` function that gets called in https://github.com/kahypar/kahypar/blob/eefba75cf3b26d4c53f86bfb66767f9521181f83/lib/libkahypar.cc#L79-L90 before we call the `kahypar::Hypergraph` constructor, which would adjust `index_vector` and `edge_vector` accordingly if any duplicate pins are present.

The cleanest approach actually would be to move the logic of ignoring duplicate pins into the hypergraph constructor itself. I can try to look into that as soon as I find some time, but you'd be more than welcome to create a PR yourself if you feel comfortable with implementing this.

**Comment by SebastianSchlag** [comment]
@Coloquinte, I just wanted to follow up on this briefly. @N-Maas is currently adding extensive input validations to surface issues like this properly to the user: https://github.com/kahypar/kahypar/pull/167

**Comment by Coloquinte** [comment]
@SebastianSchlag Thank you very much for the follow up. That's nice to have!
