### ISSUE TITLE
[Feature request] Interface for user defined objective functions

### ISSUE THREAD

**Issue by PabloAndresCQ** [kahypar/kahypar#113]
**Context**
The research group I am part of has used KaHyPar in the past to solve an optimization problem in quantum computing (see [publication](https://arxiv.org/abs/1811.10972)).
We are resuming this line of work and, to do so, it would be helpful to be able to define our own objective functions for KaHyPar to minimize.

**The request** 
We were hoping you would be willing to provide an interface for users to define custom objective functions as an alternative to the cut-net and the connectivity (λ − 1) metrics provided with KaHyPar.

Ideally, the user would create their own class inheriting from the `Metrics` class (currently a struct in `kahypar/partition/metrics.h`) and provide a custom implementation for its member functions `getMetric` and `updateMetric`.
We only require such a custom objective function to be used by the direct k-way approach.

**Trade-offs** 
- We understand KaHyPar was designed with the cut-net and (λ − 1) metrics in mind. Thus, its behaviour on custom objective functions cannot be easily predicted. This is acceptable to us: we are only hoping this to be an experimental feature.
- We understand that the efficiency of such a custom objective function would make a large impact on the runtime of KaHyPar.
- The user interface need not be particularly user-friendly.

**Comment by SebastianSchlag** [comment]
Hi @PabloAndresCQ, thanks for reaching out.

> Ideally, the user would create their own class inheriting from the Metrics class (currently a struct in kahypar/partition/metrics.h) and provide a custom implementation for its member functions getMetric and updateMetric.
> We only require such a custom objective function to be used by the direct k-way approach.

Unfortunately, it won't be that easy to extend KaHyPar with a new objective function. The `Metrics` class (which, by the way, I really should refactor at some point) is just a container to store the intermediate objective function values during uncoarsening and refinement. The actual optimization of those is tightly coupled to the individual refinement algorithms for efficiency reasons. For the direct k-way approach for example, there exist specialized implementations for [cut-net](https://github.com/kahypar/kahypar/blob/master/kahypar/partition/refinement/kway_fm_cut_refiner.h) and [connectivity](https://github.com/kahypar/kahypar/blob/master/kahypar/partition/refinement/kway_fm_km1_refiner.h) optimization. So any new objective function would necessitate to actually implement a refinement algorithm as well. Would that be something that you'd be interested in?

It might also be worthwhile to reach out to @kittobi1992 (who is still at KIT) for potential collaborations.

**Comment by PabloAndresCQ** [comment]
Hi @SebastianSchlag, thanks for your prompt reply.

> The actual optimization of those is tightly coupled to the individual refinement algorithms for efficiency reasons. For the direct k-way approach for example, there exist specialized implementations for [cut-net](https://github.com/kahypar/kahypar/blob/master/kahypar/partition/refinement/kway_fm_cut_refiner.h) and [connectivity](https://github.com/kahypar/kahypar/blob/master/kahypar/partition/refinement/kway_fm_km1_refiner.h) optimization. So any new objective function would necessitate to actually implement a refinement algorithm as well. Would that be something that you'd be interested in?

I see, that makes sense. I have had a quick look at your [dissertation](https://publikationen.bibliothek.kit.edu/1000105953) to get a better idea of how the refinement algorithm works. Is this dissertation an up to date source to read about the refinement algorithm or would you suggest some other reference? I believe there are natural candidates for a gain function and a delta-gain function for the objective function we are interested in.

We are entertaining the idea of forking your repository to implement our objective function and adapt the refinement algorithm as necessary. It would be very helpful to have a one-off conversation with someone familiar with your algorithm at a conceptual level and with the source code, so that they can help us assess how much work would it take to tailor KaHyPar to our objective function. Would you (or someone at KIT) be willing to have a chat about this?

Feel free to close this issue, we can continue this discussion via e-mail if you prefer to do so.

**Comment by SebastianSchlag** [comment]
> Hi @SebastianSchlag, thanks for your prompt reply.
> 
> > The actual optimization of those is tightly coupled to the individual refinement algorithms for efficiency reasons. For the direct k-way approach for example, there exist specialized implementations for [cut-net](https://github.com/kahypar/kahypar/blob/master/kahypar/partition/refinement/kway_fm_cut_refiner.h) and [connectivity](https://github.com/kahypar/kahypar/blob/master/kahypar/partition/refinement/kway_fm_km1_refiner.h) optimization. So any new objective function would necessitate to actually implement a refinement algorithm as well. Would that be something that you'd be interested in?
> 
> I see, that makes sense. I have had a quick look at your [dissertation](https://publikationen.bibliothek.kit.edu/1000105953) to get a better idea of how the refinement algorithm works. Is this dissertation an up to date source to read about the refinement algorithm or would you suggest some other reference? I believe there are natural candidates for a gain function and a delta-gain function for the objective function we are interested in.

Yes, the dissertation is the most in-depth resource for the FM-based refinement algorithms. For the flow-based refinement algorithm, the most recent paper is [this](https://drops.dagstuhl.de/opus/volltexte/2020/12085/pdf/LIPIcs-SEA-2020-11.pdf).

> 
> We are entertaining the idea of forking your repository to implement our objective function and adapt the refinement algorithm as necessary. It would be very helpful to have a one-off conversation with someone familiar with your algorithm at a conceptual level and with the source code, so that they can help us assess how much work would it take to tailor KaHyPar to our objective function. Would you (or someone at KIT) be willing to have a chat about this?
> 

My spare time is currently very limited, unfortunately. I might find some on the weekend in a couple of weeks. Maybe you, @kittobi1992 would be willing to help out from KIT-side of things given that you know quite a bit as well about implementing 
FM-based refinement algorithms?

**Comment by kittobi1992** [comment]
Hi @PabloAndresCQ,

this is quite interesting and I am interested in collaborating on this. As @SebastianSchlag already mentioned, it is not straightforward as one might think to implement a new metric. There are many implementation-specific details using special properties of some objective function that do not apply to others. However, it could be interesting to extract a common interface for a particular class of objective functions and try to integrate that.

Maybe we should schedule a meeting and discuss that further. What do you think? You can send me mail and we continue the discussion there: https://algo2.iti.kit.edu/members_heuer.php

**Comment by kittobi1992** [comment]
Hi @PabloAndresCQ,

I am currently working on a change that seperates the gain computation/objective functions from our refinement algorithms in Mt-KaHyPar. Mt-KaHyPar is the shared-memory parallelization of KaHyPar, which is publicly available:
https://github.com/kahypar/mt-kahypar
The change is still work-in-progress and will be available in two months from now. If you are still interested in the feature, you may want to try Mt-KaHyPar and find out if it meets your requirements. However, implementing a custom objective function will be still no trivial task, but it can be integrated then without touching the refinement algorithms.

If you want to find out more about Mt-KaHyPar you can checkout our latest technical report (submitted to ACM Journal of Algorithms):
https://arxiv.org/pdf/2303.17679.pdf

**Comment by SebastianSchlag** [comment]
HI @PabloAndresCQ ,

just to follow up: @kittobi1992 now added support for custom gain computations in Mt-KaHyPar: https://github.com/kahypar/mt-kahypar/tree/master/mt-kahypar/partition/refinement/gains
