### ISSUE TITLE
problem when building kahypar 

### ISSUE THREAD

**Issue by Tim640** [kahypar/kahypar#114]
Hello!
I'm trying to build the KaHypar and using the following commands:

```
mkdir build && cd build
cmake .. -DCMAKE_BUILD_TYPE=RELEAS -DKAHYPAR_USE_MINIMAL_BOOST=ON
make
```

but I got some errors:

[ 31%] Linking CXX shared library libkahypar.so
/usr/bin/ld: ../libmini_boost.a(cmdline.cpp.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
../libmini_boost.a: 无法添加符号: 错误的值
collect2: error: ld returned 1 exit status
lib/CMakeFiles/kahypar.dir/build.make:97: recipe for target 'lib/libkahypar.so' failed
make[2]: *** [lib/libkahypar.so] Error 1
CMakeFiles/Makefile2:3478: recipe for target 'lib/CMakeFiles/kahypar.dir/all' failed
make[1]: *** [lib/CMakeFiles/kahypar.dir/all] Error 2
Makefile:145: recipe for target 'all' failed
make: *** [all] Error 2

My system is:

ubuntu version 16.04
cmake version 3.23.1
gcc version 9.4.0

Thanks for your help!

**Comment by SebastianSchlag** [comment]
Hi,

the answer seems to be buried in the error message: `recompile with -fPIC`

Could you please try:

```
rm -rf build
mkdir build && cd build
cmake .. -DCMAKE_BUILD_TYPE=RELEAS -DKAHYPAR_USE_MINIMAL_BOOST=ON -DCMAKE_POSITION_INDEPENDENT_CODE=ON
make
```
?

`-DCMAKE_POSITION_INDEPENDENT_CODE=ON` should set the correct flags that you seem to need.

**Comment by Tim640** [comment]
Hi Sebastian,

Thanks for your reply. I tried and got this:

[ 59%] Linking CXX executable k_way_fm_refiner_test
Running k_way_fm_refiner_test
Running main() from gtest_main.cc
[==========] Running 3 tests from 2 test cases.
[----------] Global test environment set-up.
[----------] 2 tests from AKwayFMRefinerDeathTest
[ RUN      ] AKwayFMRefinerDeathTest.ConsidersSingleNodeHEsDuringInitialGainComputation
[kway_fm_cut_refiner.h:1004:initializeGainCacheFor]: Assertion `_hg.edgeSize(he) > 1` failed: he = 1 
*** stack smashing detected ***: /home/tao/kahypar/build/tests/partition/refinement/k_way_fm_refiner_test terminated
/bin/sh: 行 1:  2532 /home/tao/kahypar/build/tests/partition/refinement/k_way_fm_refiner_test
tests/partition/refinement/CMakeFiles/k_way_fm_refiner_test.dir/build.make:99: recipe for target 'tests/partition/refinement/k_way_fm_refiner_test' failed
make[2]: *** [tests/partition/refinement/k_way_fm_refiner_test] Error 134
make[2]: *** Deleting file 'tests/partition/refinement/k_way_fm_refiner_test'
CMakeFiles/Makefile2:2639: recipe for target 'tests/partition/refinement/CMakeFiles/k_way_fm_refiner_test.dir/all' failed
make[1]: *** [tests/partition/refinement/CMakeFiles/k_way_fm_refiner_test.dir/all] Error 2
Makefile:145: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by SebastianSchlag** [comment]
Interesting. Seems like something might have changed in gtest. The failure is okay though. As the name `AKwayFMRefinerDeathTest` suggest, the expected behavior is actually to trigger the assertion and therefore to fail/crash. This is why the test uses the `ASSERT_DEBUG_DEATH` gtest macro.
 I'll have to investigate why this resulted in `stack smashing` in your case though.

If you just run `make KaHyPar` you can build the main executable, which works as expected.

**Comment by SebastianSchlag** [comment]
The test passes in our CI environment: https://github.com/kahypar/kahypar/runs/6382487801?check_suite_focus=true

**Comment by SebastianSchlag** [comment]
Actually, I just realized what is going on:
Those death tests assume `DEBUG` builds for the assertions being triggered. In `DEBUG` mode, the test outputs 

```
Running k_way_fm_refiner_test
Running main() from gtest_main.cc
[==========] Running 3 tests from 2 test cases.
[----------] Global test environment set-up.
[----------] 2 tests from AKwayFMRefinerDeathTest
[ RUN      ] AKwayFMRefinerDeathTest.ConsidersSingleNodeHEsDuringInitialGainComputation
[kway_fm_cut_refiner.h:initializeGainCacheFor:1004]: Assertion `_hg.edgeSize(he) > 1` failed: he = 1
[       OK ] AKwayFMRefinerDeathTest.ConsidersSingleNodeHEsDuringInitialGainComputation (3 ms)
[ RUN      ] AKwayFMRefinerDeathTest.ConsidersSingleNodeHEsDuringInducedGainComputation
[kway_fm_cut_refiner.h:initializeGainCacheFor:1004]: Assertion `_hg.edgeSize(he) > 1` failed: he = 1
[       OK ] AKwayFMRefinerDeathTest.ConsidersSingleNodeHEsDuringInducedGainComputation (1 ms)
[----------] 2 tests from AKwayFMRefinerDeathTest (4 ms total)

[----------] 1 test from AKwayFMRefiner
[ RUN      ] AKwayFMRefiner.KnowsIfAHyperedgeIsFullyActive
[       OK ] AKwayFMRefiner.KnowsIfAHyperedgeIsFullyActive (0 ms)
[----------] 1 test from AKwayFMRefiner (0 ms total)

[----------] Global test environment tear-down
[==========] 3 tests from 2 test cases ran. (4 ms total)
[  PASSED  ] 3 tests.
[100%] Built target k_way_fm_refiner_test
```
on my local machine.

You accidentally build in `DEBUG` mode as well, because I messed up a line in my comment above.

the first flag for the cmake command should be ` -DCMAKE_BUILD_TYPE=RELEASE` - not `-DCMAKE_BUILD_TYPE=RELEAS`.

**Comment by SebastianSchlag** [comment]
To avoid accidentally building in `DEBUG` mode in the future, I hard-coded a few allowed build type options and now make sure that `cmake` fails if the build type os not set properly: https://github.com/kahypar/kahypar/commit/54c5744004c98a5d8a8841cfec4f5697db06bac8

**Comment by Tim640** [comment]
Thanks for all your help. I have built KaHyPar successfully. I really appreciate it.
