### ISSUE TITLE
Disable logging for library version?

### ISSUE THREAD

**Issue by profmadden** [kahypar/kahypar#116]
I'm not seeing an easy way to disable logging output when calling the library routines.  I'll be calling the partitioner millions of times in a run, and would like to have it not report details for each call.

What's the right way to do this?  I'm not seeing anything in the config.ini files (where I thought it might be), and no obvious compile-time switches.

Thanks very much for the great work!

**Comment by SebastianSchlag** [comment]
Hey @profmadden , thanks for reaching out. 

There actually is a config parameter to silence KaHyPar. Unfortunately, it was only documented when running `./KaHyPar --help`:

Adding
```
quiet=1
```
to the config file you use should disable all logging outputs.

**Comment by SebastianSchlag** [comment]
I added some explicit documentation to the README: https://github.com/kahypar/kahypar/commit/48d3c2e0454884a08631776869d26e9731cee63e.

**Comment by profmadden** [comment]
Fantastic -- thank you very very much.  I was sure there was an easy way to do it, but didn't see it.
