### ISSUE TITLE
Fixed vertices in the C/C++ interface?

### ISSUE THREAD

**Issue by profmadden** [kahypar/kahypar#117]
How can I specify that some vertices are fixed to a partition from the C/C++ interface?  I tried setting the partition numbers for some vertices to a value other than -1, but this seems to be ignored.  There's a --fixed option for the command line, so I'm sure there's a way to do it, but I'm not seeing it.

Thanks very much!

**Comment by profmadden** [comment]
Ahh -- after a little bit more digging --
* create the hypergraph with kahypar_create_hypergraph()
* kahypar_set_fixed_vertices() call to set the fixed vertices
* kahypar_partition_hypergraph(), using the updated graph
In hMetis, the fixed vertices are picked up directly from the incoming partition array, versus a separate call here.  All seems to work, so I'll close this issue.

Thanks again for all the work you've put into this!

**Comment by SebastianSchlag** [comment]
Hey @profmadden,
sorry for the late reply. I agree that the C/C++ interface documentation isn't great. Glad that you found out how to do it. 😊

**Comment by profmadden** [comment]
I may write up a how-to, and have some sample code.  I'm flying KaHyPar in as a replacement to a tool that currently uses hMetis (which has not been updated in a zillion years, and may never get updated).  I'll let you know when I've got something together; might be good to toss into a Wiki or README somewhere.
