### ISSUE TITLE
Questions about precompiled python pip package

### ISSUE THREAD

**Issue by skyshine102** [kahypar/kahypar#118]
Hi, I would like to know if the precompiled version of kahypar uses boost library.
I am using the great python interface with "km1_kKaHyPar_sea20.ini" to process a large circuit with 1357317 nodes and 1603258 nets, k = 2500, epsilon=0.03. It takes more than 3 days to run. I was wondering if it is the precompiled version that limits the speed. 
Can the authors give me some hints about how to deal with this kind of cases if I want the partitioning to be competed in 5 hours? Like how can I adjust the .ini configs or suggestions on using multi-threaded version / re-build the kahypar package from source.

Thank you.

**Comment by larsgottesbueren** [comment]
Hello there,

This should not be an issue with precompilation or boost.

k=2500 is fairly big, which will slow down initial partitioning massively. At least that's my guess. There are better methods for large k than the current initial partitioning in kahypar.
Your best bet is to try our (much faster) parallel version, which is available at https://github.com/kahypar/mt-kahypar.
This code doesn't have a python interface yet, so you're stuck with using the binary or C++ lib interface. Try the default config, and if it still takes too long, disable FM by setting --r-fm-type=do_nothing on the command line. If you have trouble getting it running, feel free to send me an email with your instance in hMetis format.

We're always happy to help, so feel free to reach out with any questions or suggestions.

**Comment by SebastianSchlag** [comment]
Hi @skyshine102, 
Thanks for reaching out and sorry for the late reply. I’m currently on vacation with very limited internet access. 
@larsgottesbueren is probably right. KaHyPar is more geared towards moderate values of k - at least the direkt k-way version. For large values of k, it’s refinement algorithms become slow. 
One thing that you could try is to use the recursive bipartitioning configuration (called rKaHyPar in the README). This config should run significantly faster.

**Comment by skyshine102** [comment]
Hi, thank you @SebastianSchlag @larsgottesbueren for answering my question. I will try rKaHyPar first then mt-kahypar to see if I can do it in reasonable time.

**Comment by SebastianSchlag** [comment]
Sounds good. Please feel free to reach out again if you run into any further problems.
