### ISSUE TITLE
Char type problem on ARM CPUs

### ISSUE THREAD

**Issue by Takumi-Honda** [kahypar/kahypar#123]
https://github.com/kahypar/kahypar/blob/1207f56a0001e1b819e8cf404ca692a2499c7f0b/kahypar/partition/refinement/2way_fm_refiner.h#L576

Char is unsigned char on ARM CPUs. 
It means that the range of char type on ARM is from 0 to 255 and does not work with negative values.

https://developer.arm.com/documentation/den0013/d/Porting/Miscellaneous-C-porting-issues/unsigned-char-and-signed-char

**Comment by SebastianSchlag** [comment]
Hi @Takumi-Honda, good catch! Thanks for pointing this out. 👍
