### ISSUE TITLE
loadINIconfiguration error on Python MacOS M1 interface

### ISSUE THREAD

**Issue by andreadegirolamo99** [kahypar/kahypar#127]
I successfully installed and built KaHyPar and moved the .so file in the site-packages directory of my Miniconda environment. After this, the code seems to compile correctly, however I have issues trying to setup the configuration of a context, in particular with the method loadINIconfiguration. I copied the template Python code in the README file in a Jupyter notebook cell, just to test the library, and either the kernel dies, or I get this runtime error: 

`RuntimeError: the option 'mode' is required but missing`

The path I'm inserting is in the following form:

`context.loadINIconfiguration("/Users/(path_to_kahypar)/kahypar/config")`

Do you have an idea of what might be going on here?

**Comment by SebastianSchlag** [comment]
Hi @andreadegirolamo99,

first of all: Sorry for the late reply. It has been a busy week.

Did you change something in the `ini` file? It looks like the line `mode=direct` might be missing. Which configuration are you using?

I just reproduced the steps from the README on my M2 Mac and everything seems to work as expected.

**Comment by andreadegirolamo99** [comment]
Hi @SebastianSchlag,

No worries, better late than never!

Actually, I should be the one apologising, since I was making a mistake in the path, not inserting the actual file I wanted to load 😅.

I also executed the procedure just like described in the README, except for one thing, which is I couldn't directly access the kahypar directory like this: `git@github.com:SebastianSchlag/kahypar.git`
If I try to do it as written in the README, it says: 

`git@github.com: Permission denied (publickey).`
`fatal: Could not read from remote repository.`
`Please make sure you have the correct access rights`
`and the repository exists.`

I just basically copied the HTTPS directory of the directory and inserted it in the command replacing what I had before. So finally the command looks something like: `git clone --depth=1 --recursive https://github.com/kahypar/kahypar.git`, which should be totally equivalent.

By the way, everything is working totally fine now, thanks for your help :)

**Comment by SebastianSchlag** [comment]
Hehe, no worries! Glad that everything works now. 🙂
