### ISSUE TITLE
How to configure KaHyPar to get a high quality solution regardless of running time?

### ISSUE THREAD

**Issue by onefanwu** [kahypar/kahypar#133]
Hello, KaHyPar is an excellent hypergraph partitioning tool that offers many flexible parameter configurations. In my application scenario, I don't care much about the runtime and require high quality of the solution. I wonder if you can provide suggestions on how to configure the ini file in terms of parameters to get the highest quality solution.

**Comment by SebastianSchlag** [comment]
Hi @onefanwu,
The cut/km1_kkahypar_sea20.ini config files give the highest solution quality. The evolutionary algorithm (i.e. the km1_kkahypar-e-sea20.ini) might give a bit better solutions but the running time can be significantly larger. For this configuration, you can use the —time_limit parameter to set the maximum running time.

**Comment by onefanwu** [comment]
Thanks so much for your helpful answers!
