### ISSUE TITLE
some questions in fixed vertex way

### ISSUE THREAD

**Issue by CL-liao** [kahypar/kahypar#134]
![image](https://user-images.githubusercontent.com/92159432/202892895-844cf53a-95c5-4949-8d61-1c89c90512b5.png)
Hi,I want to ask when this problem will occur.

**Comment by SebastianSchlag** [comment]
Hi @CL-liao, thanks for reaching out. This can happen for certain weighted instances that are difficult to partition in a balanced fashion (e.g. if the imbalance parameter epsilon is too small). 
In these situations, it might help to try the different contraction policies mentioned in the [README](https://github.com/kahypar/kahypar#additional-features).
