### ISSUE TITLE
Mac arm64 install fails on missing googletest, pybind11 CMakeLists; precompiled via pypi fails too

### ISSUE THREAD

**Issue by rbelew** [kahypar/kahypar#136]
Following your install instructions:

`cmake .. -DCMAKE_BUILD_TYPE=RELEASE -DKAHYPAR_PYTHON_INTERFACE=1`

> -- Found Threads: 
> CMake Error at CMakeLists.txt:20 (add_subdirectory):
>   The source directory
> 
>     /Users/rik/data/git/kahypar-master/external_tools/googletest
> 
>   does not contain a CMakeLists.txt file.
> 
> -- Boost Include: /Users/rik/data/pkg/miniconda3/envs/metis/include
> -- Boost Library Dirs: /Users/rik/data/pkg/miniconda3/envs/metis/lib
> -- Boost Libraries: Boost::program_options
> -- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
> -- No git refspec detected
> -- CMAKE_CXX_FLAGS:  -mcrc32  -std=c++1y -Wno-register
> -- CMAKE_CXX_FLAGS_RELEASE: -O3 -DNDEBUG -O3
> -- CMAKE_CXX_FLAGS_DEBUG: -g -pthread -g3
> CMake Error at python/CMakeLists.txt:13 (add_subdirectory):
>   The source directory
> 
>     /Users/rik/data/git/kahypar-master/python/pybind11
> 
>   does not contain a CMakeLists.txt file.
> 
> CMake Error at python/CMakeLists.txt:15 (pybind11_add_module):
>   Unknown CMake command "pybind11_add_module".

I also tried installing the precompiled version via pypi:

`python3 -m pip install --index-url https://pypi.org/simple/ --no-deps kahypar`

> Collecting kahypar
>   Downloading kahypar-1.1.7-cp38-cp38-macosx_11_0_arm64.whl (885 kB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 885.8/885.8 kB 14.6 MB/s eta 0:00:00
> Installing collected packages: kahypar
> Successfully installed kahypar-1.1.7

So far so good!  But then trying to import

> % python 
> Python 3.8.11 (default, Jul 29 2021, 14:57:32) 
> [Clang 12.0.0 ] :: Anaconda, Inc. on darwin
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import kahypar
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> ImportError: dlopen(/Users/rik/data/pkg/miniconda3/lib/python3.8/site-packages/kahypar.cpython-38-darwin.so, 0x0002): tried: '/Users/rik/data/pkg/miniconda3/lib/python3.8/site-packages/kahypar.cpython-38-darwin.so' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))
> >>> 

(This may be related to #103 but I have both cmake and boost.)

**Comment by SebastianSchlag** [comment]
Hi @rbelew, thanks for reaching out.

What type of OS are you using? Seems like you are on an Intel Mac. I think we only have precompiled binaries for M1/M2 Macs at the moment.


> The source directory
> /Users/rik/data/git/kahypar-master/external_tools/googletest
> does not contain a CMakeLists.txt file.

and

> The source directory
> /Users/rik/data/git/kahypar-master/python/pybind11
> does not contain a CMakeLists.txt file.

Those two errors are interesting and seem to indicate that you haven't cloned KaHyPar properly / initialized the submodules. Both `pybind11` and `googletest` are [imported](https://github.com/kahypar/kahypar/blob/master/.gitmodules) as submodules.
Could you try to either
- run `git submodule init` and then `git submodule update` in the KaHyPar root director
- clone KaHyPar again using the command provided in the README

and then trying to run `cmake` from a clean build directory again?

My guess is that those might solve your problem.

**Comment by rbelew** [comment]
Hello @SebastianSchlag thank for your quick response!

>  you haven't cloned KaHyPar properly

indeed!  i had just grabbed the .git file and made from that, and so it missed the `--depth=1 --recursive` bit your instructions included; now it throws bunches of (iterator deprecated) warnings but it makes and tests pass!  

I am on an Apple M1 Pro.  i also saw the "...is an incompatible architecture (have (x86_64)" comment when trying the binary import, which confuses me, too.  but i with the -DKAHYPAR_PYTHON_INTERFACE=1 flag i am able to import into python , so i'm not too concerned.

thanks very much!
