### ISSUE TITLE
doxygen isn't making API doc?

### ISSUE THREAD

**Issue by rbelew** [kahypar/kahypar#137]
here's hoping this issue is just as simple!

cmake finds doxygen

> -- Found Doxygen: /Users/rik/data/pkg/miniconda3/envs/metis/bin/doxygen (found version "1.9.5") found components: doxygen dot 

and this paragraph of CMakeLists made me think it should generate doc:

> add a target to generate API documentation with Doxygen
> find_package(Doxygen)
> if(DOXYGEN_FOUND)
> configure_file(${CMAKE_CURRENT_SOURCE_DIR}/Doxyfile.in ${CMAKE_CURRENT_BINARY_DIR}/Doxyfile.in @ONLY)
> add_custom_target(doc
> ${DOXYGEN_EXECUTABLE} ${CMAKE_CURRENT_BINARY_DIR}/Doxyfile.in
> WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}
> COMMENT "Generating API documentation with Doxygen" VERBATIM)
> endif(DOXYGEN_FOUND)

but i don't get the comment it mentions, and no documentation seems to be generated?

**Comment by SebastianSchlag** [comment]
Yep, that's an easy one: `make doc` should generate the doxygen documentation in your build folder. 🙂

**Comment by rbelew** [comment]
Cmake/make is still spooky stuff for me.  I could see it make the `doc` target but didn't realize making with it explicitly was an additional step.  Easy indeed, thanks again.
