### ISSUE TITLE
loading .metis graph file

### ISSUE THREAD

**Issue by rbelew** [kahypar/kahypar#138]
i want to use some standard graphs (eg, add20, http://www.cise.ufl.edu/research/sparse/matrices/Hamm/add20.html) for testing of kahypar.  but when i specify it via the -h argument, it seems to be misinterpreted: this graph has n=2395 vertices and ne=7462 edges. but kahypar produces a partition with 7462 entries?!

i find this `graph_to_hgr_converter` tool here: https://github.com/kahypar/kahypar/blob/master/tools/graph_to_hgr_converter.cc, and perhaps i need to preprocess these graphs first to make them kahypar hypergraphs?

Sorry to be such a high-maintenance early user(:

**Comment by SebastianSchlag** [comment]
Hey @rbelew no worries! 🙂 Sorry for the delayed response.

Yes, that is correct. KaHyPar uses the same [format](http://glaros.dtc.umn.edu/gkhome/fetch/sw/hmetis/manual.pdf) as `hMetis`, which is different from the standard Metis format. You can use the `graph_to_hgr_converter` for this, which can be built through `make GraphToHgr`.

**Comment by rbelew** [comment]
thanks again!
