### ISSUE TITLE
Segmentation fault if npartitions =1

### ISSUE THREAD

**Issue by JoeyT1994** [kahypar/kahypar#139]
I know this is an edge case but if you ask for 1 partition then you get a segmentation fault.

This is on the Julia Version (tested on a Linux workstation):

```using KaHyPar
using SparseArrays

I = [1,3,1,2,4,5,4,5,7,3,6,7]
J = [1,1,2,2,2,2,3,3,3,4,4,4]
V = Int.(ones(length(I)))

A = sparse(I,J,V)

h = KaHyPar.hypergraph(A)

KaHyPar.partition(h,1,configuration = :edge_cut)
```

yields:

![image](https://user-images.githubusercontent.com/51231103/211874537-8b2bc209-fd54-4505-b9d2-6000e021e9ed.png)

I imagine this error might occur on all versions - not just the Julia one.

Whilst I know it doesn't make sense to ask for 1 partition, I imagine the code should ideally just return a single partition with all the vertices of the graph in it.

**Comment by SebastianSchlag** [comment]
Hey @JoeyT1994, thanks for bringing this to our attention. While this is truly a degenerate edge case, I totally agree that we shouldn't crash. We've addressed this in https://github.com/kahypar/kahypar/pull/140.

**Comment by SebastianSchlag** [comment]
I just updated the python packages. @jalving could you please update the Julia package?

**Comment by JoeyT1994** [comment]
Thanks for addressing this @SebastianSchlag !

**Comment by jalving** [comment]
@SebastianSchlag yep, sure thing. I'll kick off a new Julia binary when I can get a chance.

**Comment by SebastianSchlag** [comment]
> @SebastianSchlag yep, sure thing. I'll kick off a new Julia binary when I can get a chance.

@jalving Awesome, thanks a lot! 👍
