### ISSUE TITLE
time complexity

### ISSUE THREAD

**Issue by jcmgray** [kahypar/kahypar#141]
Hi there, I had a (quickish) skim of the various kahypar papers but couldn't find anything definitive to this question. Essentially, is there a known / estimated / observed runtime complexity for a single `kahypar` partitioning with number of nodes $N$ (if it helps, optionally for bounded node/edge degree $k$)? I realize this may well depend on many factors and have no clear answer - my sense is that it is 'close' to linear but wanted to check. Apologies if this is in one of the publications and I missed it.

**Comment by SebastianSchlag** [comment]
Hi @jcmgray, no you didn't miss anything. We don't have any theoretical running time guarantees. To the best of our knowledge, deriving performance guarantees for multi-level partitioning algorithms used in practice is still an open problem.

**Comment by jcmgray** [comment]
OK, thanks for the reply. I guess I'll see at some point if I can extract a *very rough* typical observed scaling.

**Comment by SebastianSchlag** [comment]
> OK, thanks for the reply. I guess I'll see at some point if I can extract a _very rough_ typical observed scaling.

Sounds great! 👍 Please let us know! :

**Comment by jcmgray** [comment]
I ran some quick tests, bipartitioning random ksat instances:

![index-tn](https://user-images.githubusercontent.com/8982598/215914771-38389a5c-b20c-4ac5-8646-6edbe61e32b4.svg)

These are pretty non-local and 'hard' to partition I imagine.

* `num_variables` => number of hyperedges.
* `alpha` => average number of nodes per hyperedge

Looks relatively linear for small to medium sizes:

![index](https://user-images.githubusercontent.com/8982598/215914505-02961c83-0e7a-430d-9c03-a6131499516d.svg)

Including bigger sizes it looks a maybe little super linear:

![index2](https://user-images.githubusercontent.com/8982598/215914921-eef00b48-51a7-467b-868e-57662d8ff9ea.svg)

Here's the log-log version:

![index3](https://user-images.githubusercontent.com/8982598/215915118-4779298d-d9e1-493d-b379-db34fa17b1fe.svg)
