### ISSUE TITLE
Python import error on Mac M1: "Illegal instruction: 4"

### ISSUE THREAD

**Issue by venktesh22** [kahypar/kahypar#143]
I am unable to import kahypar library on my MacBook with an M1 Pro Chip. The code stops with the following error and no other message:
`Illegal instruction: 4`
My OS version is macOS Monterey 12.2.1. I realize that this is similar to other library import issues and I have tried various options (such as reinstalling conda based on this resource https://github.com/conda/conda/issues/9678). All other libraries work on my machine, though kahypar still continues to give me an error.

Any help would be appreciated. Thanks.

**Comment by SebastianSchlag** [comment]
Hi @venktesh22,
thanks for reaching out. This is odd.. we actually support M1 Macs since [early January 2022](https://github.com/kahypar/kahypar/issues/98) and I'm running KaHyPar on M1 and M2 Macs myself.
 
Are you building the KaHyPar python interface from source or are you installing the package through `pip`? Which python version are you using?

**Comment by venktesh22** [comment]
Thanks @SebastianSchlag for the response. I had used `pip` for the installation with python version 3.5.6. Looking at the other issue you referenced helped. I was using conda installation based on x86_64 and upgrading to arm-64 version fixed the import issue. I am now able to use kahypar!
https://github.com/kahypar/kahypar/issues/98#issuecomment-1014777901

However, I am running into errors with other libraries in the environment that won't work with the upgrade. I am curious, is there a way to still use KaHyPar on virtual environments that are based on x86_64 python packages? Thanks again for the help.

**Comment by venktesh22** [comment]
I found a resolve where I could upgrade the other libraries to the arm-64 version and now all imports work as expected. I will close the issue. Thanks for the help.

**Comment by SebastianSchlag** [comment]
> I found a resolve where I could upgrade the other libraries to the arm-64 version and now all imports work as expected. I will close the issue. Thanks for the help.

Nice! I'm glad that you could resolve the issue. Thanks for keeping us in the loop!
