### ISSUE TITLE
parsing command line arguments

### ISSUE THREAD

**Issue by rbelew** [kahypar/kahypar#146]
i'm using clojure to make shell calls of kahypar, but the same call i can successfully make from command line is not working when invoked this way.  i can imagine your response is "it must be a clojure problem then," but i want to show you some tests that make me not think so:

the command line is this

`kahypar -k 2 -e 0.03 -m direct -o cut -w true -p .../baseConfig-direct.ini -h .../g0.hgr`

when I create this command in clojure and use its `clojure.java.shell/sh` (which is actually a call to Java's `Runtime.exec()`)

i get the following error from boost:

`khpEval: exit=134 err=libc++abi: terminating with uncaught exception of type boost::wrapexcept<boost::program_options::invalid_option_value>: the argument (' 2 -e 0.03 -m direct -o cut -w true -p .../baseConfig-direct.ini -h .../g0.hgr') for option '--blocks' is invalid`

but if i replace the call to kahypar with a call to this simple `echoArgs.sh` script

```
#!/bin/bash
echo "echo:"
echo "$@"
echo "printf"
printf '%s\n' "$*"
```

it echos **EXACTLY THE SAME ARGUMENTS** as on the command line:

```
echo:
-k 2 -e 0.03 -m direct -o cut -w true -p ...baseConfig-direct.ini -h .../g0.hgr
printf
-k 2 -e 0.03 -m direct -o cut -w true -p ...baseConfig-direct.ini -h .../g0.hgr
```

so i am left to believe it is boost/kahypar argument parsing that's the issue?

**Comment by SebastianSchlag** [comment]
Hey @rbelew, thanks for reaching out. This seems to be very weird indeed. I haven't seen any issue like this before. 

The error message

```
the argument (' 2 -e 0.03 -m direct -o cut -w true -p .../baseConfig-direct.ini -h .../g0.hgr') for option '--blocks' is invalid

``

**Comment by SebastianSchlag** [comment]
Hey @rbelew, thanks for reaching out. This seems to be very weird indeed. I haven't seen any issue like this before. 

The error message

```
the argument (' 2 -e 0.03 -m direct -o cut -w true -p .../baseConfig-direct.ini -h .../g0.hgr') for option '--blocks' is invalid

```

is interesting though. For some reason, it seems like _all_ the parameters are parsed as belonging to the `-k`/`--blocks` argument. Could this be some kind of whitespace issue where in the parameter string that works the arguments are separated correctly by spaces and in the other string there's a different character that just appears as a space in the output?

**Comment by rbelew** [comment]
thanks for your quick response @SebastianSchlag ! something like that.  i can send you the results of other experiments where it gets farther when i remove SPACES (eg, "-k 2" --> "-k2") on provided parameters.  

when i do that to all of the parameters it chokes on "-h <HGRfile>", complaining about a TRAILING `\n'` on the file name.  which i am confident (based on my `echoArg` experiments) is NOT something i'm passing in?

these experiments are also making me appreciate that when you say "require" they MUST be part of the call of `kahypar`?  ie, i've tried putting all the args in the config file, and it complains about missing blocks, ...

**Comment by rbelew** [comment]
ps: i've done other experiments passing a series of independent strings along to (shell/sh) vs. one string with them all in it.  also doesn't go, but with slightly different complaints.

**Comment by rbelew** [comment]
update: it now seems like this was an issue with the clojure/java side of this exchange: see last comments on this thread  https://stackoverflow.com/q/75844097/1079688
for anyone bumping into this, `(shell/sh khpPath param)` does not work but `(shell/sh "sh" "-c" (str khpPath " " param))` does!

**Comment by SebastianSchlag** [comment]
Nice! I'm glad that you could resolve the issue. Thanks for the update on how it can be fixed! 👍
