### ISSUE TITLE
Extracting graphs from ISP98.hgr files?

### ISSUE THREAD

**Issue by rbelew** [kahypar/kahypar#152]
(sorry, the last issue got posted incompletely( :

I'm trying to evaluate techiques against the ISPD98 VLSI circuit benchmark suite 
now [hosted at TILOS](https://github.com/TILOS-AI-Institute/HypergraphPartitioning/tree/main/benchmark).  

Let's use `IBM01.hgr` as an example. Using the [now removed?!](http://glaros.dtc.umn.edu/gkhome/metis/hmetis/download)
hMetis manual, I find n=11281 unique nodeIDs, and count m=14111 edges among them.

Yet the first line of the .hgr file says there are n_hgr=12752  m_hgr=14111, and
this is the number reported by [Bustani et al](https://github.com/TILOS-AI-Institute/HypergraphPartitioning/blob/main/SpecPart/SpecPart_final_submission.pdf).  They are finding 1471 more nodes than I do?

I've tried to use kahypar tools to remove my confusion.  
```
% HgrToEdgeList ibm01.hgr

% wc -l ibm01.hgr.edgelist

   50566 ibm01.hgr.edgelist
```

```
% HgrToBipartiteGraphML ibm01.hgr

% grep -c "node id=" ibm01.hgr.k2.graphml
	26863
% grep -c "edge id=" ibm01.hgr.k2.graphml
	50566
```

```
% HgrToBipartiteMetisGraph ibm01.hgr

% wc -l ibm01.hgr.graph
   26864 ibm01.hgr.graph
```
kahypar is internally consistent; all your tools report n_khp=26863, m_khp=50566. 
but these aren't the numbers i come up with, or those the file announces?!

What am I misunderstanding, please?

**Comment by SebastianSchlag** [comment]
Hi @rbelew, 

I'm not entirely sure if I understand your question.

According to the header, the `ibm01.hgr` hypergraph  has `14111` hyperedges and `12752` vertices. If you run KaHyPar in verbose mode using the `-v 1` option, the logs also show the same numbers:

```
Hypergraph Information
Name : ibm01.hgr
Type: edgeWeights=false nodeWeights=false
# HNs : 12752 # HEs : 14111 # pins: 50566
HE size             HE weight           HN degree           HN weight
| min= 2            | min= 1            | min= 1            | min= 1
| Q1 = 2            | Q1 = 1            | Q1 = 2            | Q1 = 1
| med= 2            | med= 1            | med= 3            | med= 1
| Q3 = 4            | Q3 = 1            | Q3 = 5            | Q3 = 1
| max= 42           | max= 1            | max= 39           | max= 1
| avg= 3.58345      | avg= 1            | avg= 3.96534      | avg= 1
| sd = 3.34271      | sd = 0            | sd = 2.32894      | sd = 0
```

The `HgrToEdgeList`, `HgrToBipartiteGraphML`, and `HgrToBipartiteMetisGraph` tools all covert hypergraphs into different bipartite-graph-based formats. In the bipartite graph representation, there's a node for every vertex _and_ every hyperedge in the hypergraph (hence the total of `26863` nodes in the graph) and an edge indicates that a vertex appears as a pin in a hyperedge (hence the total number of `50566` edges in the graph).

> Let's use IBM01.hgr as an example. Using the [now removed?!](http://glaros.dtc.umn.edu/gkhome/metis/hmetis/download)
> hMetis manual, I find n=11281 unique nodeIDs, and count m=14111 edges among them.

Let me paraphrase this to make sure I understand it correctly: You implemented a parser for the `hgr` file format based on the specifications outlined in the hMetis manual and if you use that to parse e.g. `ibm01.hgr` you get an incorrect number of vertices?

For reference, [here is](https://github.com/kahypar/kahypar/blob/5622a01200de0a5e1730bd5cbc18b7348f3aa9c8/kahypar/io/hypergraph_io.h#L40-L150) how we do it.

**Comment by rbelew** [comment]
@SebastianSchlag thank you for your patient reply.  it seems i'm only now bumping into .hgr files applied to HYPER-graphs!  so i've now read the Wiki entry, and also bumped into your recent [_ACM J. Exp. Algorithmics_  paper](https://dl.acm.org/doi/full/10.1145/3529090)!  i clearly need to better wrap my head around hypergraphs, pins, etc.  i'll close this as an issue.

but is there a simple way to extract the “order” of the graph, ie the number of real vertices, not hyperedges?

**Comment by SebastianSchlag** [comment]
No worries! 🙂 

>but is there a simple way to extract the “order” of the graph, ie the number of real vertices, not hyperedges?

I guess that would be the number of vertices (i.e., the second value in the `.hgr` header). But in terms of "size", the number of pins actually seems to be more appropriate for hypergraphs since neither the number of pins per hyperedge nor the number of hyperedges per vertex is bounded.
