### ISSUE TITLE
when make ,there are a problem

### ISSUE THREAD

**Issue by 936187425** [kahypar/kahypar#154]
when i am making, the error message "*** Error in `/home/panHY/New/kahypar/build/tests/io/hypergraph_io_test': double free or corruption (!prev):"

please help me! thank you!

**Comment by 936187425** [comment]
version:
gcc (GCC) 12.2.0
cmake version 3.26.3
Ubuntu 16.04.7 LTS

**Comment by 936187425** [comment]
run cmake: cmake .. -DCMAKE_BUILD_TYPE=RELEASE -DKAHYPAR_USE_MINIMAL_BOOST=ON -DCMAKE_POSITION_INDEPENDENT_CODE=ON
run make: make

**Comment by SebastianSchlag** [comment]
> * If the error doesn't appear in debug mode, try removing the two appearances of `-mtune=native -march=native` in CMakeLists.txt (lines 263 and 264, line 263 should then be `set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -O3")`) and building again in release mode (i.e., with your original cmake command)

Additionally, could you fry adding `-fsanitize=address` to the flags to run with address sanitizer. This might give more detailed information about whether there is an issue with the test.

**Comment by 936187425** [comment]
thank you!

**Comment by SebastianSchlag** [comment]
@936187425 I just wanted to check in briefly. Did any of the suggestions @N-Maas and I provided yield some more detailed information?
