### ISSUE TITLE
Meet a bug if node index is not continuous

### ISSUE THREAD

**Issue by xiachenrui** [kahypar/kahypar#158]
Hi all,

I meet a bug if my node index is not continuous, for example I change the 5 in tutorial to 100:
```python
import os
import kahypar as kahypar

num_nodes = 7
num_nets = 4

hyperedge_indices = [0,2,6,9,12]
hyperedges = [0,2,0,1,3,4,3,4,6,2, 100,6] # Change 5 to 100

k=2

hypergraph = kahypar.Hypergraph(num_nodes, num_nets, hyperedge_indices, hyperedges, k)
```
above code will rasie error. Is this expected ?

Best!
Chen-Rui

**Comment by kittobi1992** [comment]
Yes, this behaviour is expected. You initialize the hypergraph with seven nodes which are expected to have continuous node IDs. This invariant is important for performance reasons since we can use in many of our internal algorithms arrays instead of hash maps.

**Comment by xiachenrui** [comment]
Thanks a lot for your kind reply !
