### ISSUE TITLE
Run time of kahypar

### ISSUE THREAD

**Issue by xiachenrui** [kahypar/kahypar#161]
Hi all,

I am running kahypar (python version) on a hypergraph with 800 nodes and  20,208 edges, with k=10 and cut_kKaHyPar_sea20.ini. It takes more than 1 hour and still not finish. Is this expected ?

I must clarify that the size of (hyper) edges in my dataset is highly unbalanced. In detail:
- about 500 hyperedges contain 10-800 nodes
- other hyperedge only contain 2 nodes (like edges in plain graph)

Is kahypar suitable for this suitation? Should I need to change the configure to run fast?  I am  a newbie and any suggestion will be useful ! Thanks a lot !

Best !
Chen-Rui

**Comment by SebastianSchlag** [comment]
Hi @xiachenrui, it sounds like something is off - it shouldn't take that long. 

Two things that come to my mind:
- KaHyPar assumes that a vertex can only be in a hyperedge at most once. If vertices appear more than ones, the coarsening algorithm breaks and can potentially run into an infinite loop.
- Did you build the python interface yourself? If so, did you make sure compile in` RELEASE` mode? In `DEBUG` mode, KaHyPar runs really slowly, because it executes a lot of non-trivial assertions.

Could you sent us your hypergraph in hMetis format for debugging?

**Comment by xiachenrui** [comment]
Thanks @SebastianSchlag

- I check my graph and one node only occur once in one hyperedge. But I notice some edge only contain one node, maybe this is illegal. I will del these edges and try again
- I use your pre-bulided python package

I am very glad to share my hypergraph with you. It can be download from [here](https://drive.google.com/file/d/1-_uSNbzvSFI_xZ6rpJyw0tkSJolSiv1v/view?usp=sharing)

Best!

**Comment by xiachenrui** [comment]
> Thanks @SebastianSchlag
> 
> * I check my graph and one node only occur once in one hyperedge. But I notice some edge only contain one node, maybe this is illegal. I will del these edges and try again
> * I use your pre-bulided python package
> 
> I am very glad to share my hypergraph with you. It can be download from [here](https://drive.google.com/file/d/1-_uSNbzvSFI_xZ6rpJyw0tkSJolSiv1v/view?usp=sharing)
> 
> Best!

I del the edges which only contain one node , updated file can be found [here](https://drive.google.com/file/d/1-_uSNbzvSFI_xZ6rpJyw0tkSJolSiv1v/view?usp=share_link)

**Comment by N-Maas** [comment]
Hi @xiachenrui,
it seems the pins of your hyperedges start with 0 for the first node. However, the hMetis format as used by KaHyPar expects that the first index is 1. So this might be the source of your problem.

**Comment by xiachenrui** [comment]
@N-Maas Thanks !
I will fix this and try again.

Best!

**Comment by xiachenrui** [comment]
But I noticed that in your python tutorial, the index also starts from 0, such as 
``` python
hyperedge_indices = [0,2,6,9,12]
hyperedges = [0,2,0,1,3,4,3,4,6,2,5,6]

node_weights = [1,2,3,4,5,6,7]
edge_weights = [11,22,33,44]
```
I save the hypergraph to hMetis format (although not valid) only for sharing.

I notice there are some repeat hyperedges in my graph, can this raise the problem ?

**Comment by SebastianSchlag** [comment]
> But I noticed that in your python tutorial, the index also starts from 0, such as

Yes, that's correct. Only the hMetis file format expects IDs to start with `1`.

> I notice there are some repeat hyperedges in my graph, can this raise the problem ?

Repeated/parallel hyperedges with the same vertices should not be a problem. KaHyPar can deal with them.

**Comment by SebastianSchlag** [comment]
@xiachenrui I'm closing this as resolved. Please feel free to reach out again if you experience any more issues.
