### ISSUE TITLE
How to customize the size of the block?

### ISSUE THREAD

**Issue by RoccoLoter** [kahypar/kahypar#162]
Hi all,
I am using kahypar (python version) on a hypergraph. My question is how to customize the size of the block(i.e. partiton a hypergraph into k blocks, and the capacity of each block is fixed and different before partition).
I try to using the api `setCustomTargetBlockWeights` to set the related parameter, but that's not what I want. 
Best!
Luo

**Comment by N-Maas** [comment]
Hi Luo,
`setCustomTargetBlockWeights` allows to define a separate, custom size for each block prior to partitioning.
Could you explain in more detail why this is not what you want?

**Comment by RoccoLoter** [comment]
> 

Hi H-Maas:
  I will explain why this is not what I want with a simple example.
  Suppose now I have two clusters, the first cluster can only accommodate up to 10 vertices, and the second cluster can only accommodate up to 20 vertices. I want to divide a hypergraph with 35 nodes into 2 parts, and map the nodes in it to the vertices in the cluster. It is unreasonable to use the `setCustomTargetBlockWeights`, because the number of nodes contained in a certain block may be greater than 10 in the result of partition.

**Comment by kittobi1992** [comment]
Hi @RoccoLoter,
Dividing a hypergraph with 35 nodes into two blocks with maximum block weights 10 and 20 is not feasible since there are always 5 nodes which you can not assign to any block. The `setCustomTargetBlockWeights` function enforces this by verifying that the sum of the custom block weights is larger than the weight of the hypergraph. This constraint is an essential part of the definition of the partitioning problem. Maybe you can describe your concrete use case and we can find an alternative solution for your problem?

**Comment by RoccoLoter** [comment]
> Hi @RoccoLoter, Dividing a hypergraph with 35 nodes into two blocks with maximum block weights 10 and 20 is not feasible since there are always 5 nodes which you can not assign to any block. The `setCustomTargetBlockWeights` function enforces this by verifying that the sum of the custom block weights is larger than the weight of the hypergraph. This constraint is an essential part of the definition of the partitioning problem. Maybe you can describe your concrete use case and we can find an alternative solution for your problem?

Hi @kittobi1992 ,
  Sorry, there was an error in the example I gave before, now I have modified it, it should be dividing a hypergraph with 25 nodes into two blocks with maximum block weights 10 and 20. Thanks for your reply!
  Currently kahypar (python version) can customize the size of the blocks? Instead blocks are roughly equal-sized.

**Comment by kittobi1992** [comment]
Hi @RoccoLoter,
No problem. Yes, you can realise your example with the function setCustomBlockWeights([10,20]). This ensures that the first block has no more than 10 nodes and the second no more than 20 nodes.

**Comment by RoccoLoter** [comment]
Hi @kittobi1992 ，
I run a small demo using kahypar(python version), program execution failed. **Perhaps there are some limitations to the solution you are talking about?**
Part of the code is as follows:
```
    num_nodes = 7
    num_nets = 4
    hyperedge_indices = [0,2,6,9,12]
    hyperedges = [0,2,0,1,3,4,3,4,6,2,5,6]
    node_weights = [2,1,2,2,2,1,2]
    edge_weights = [11,22,33,44]

    hypergraph = kahypar.Hypergraph(num_nodes, num_nets, hyperedge_indices, hyperedges, k, edge_weights, node_weights)
    config_file = 'path-to-config/km1_kKaHyPar_sea20.ini'
    hygragh_cont = kahypar.Context()
    hygragh_cont.loadINIconfiguration(config_file)
    hygragh_cont.setK(2)
    hygragh_cont.setCustomTargetBlockWeights([5, 4])
    hygragh_cont.setEpsilon(0.01)

    kahypar.partition(hypergraph, hygragh_cont)
```

**Comment by kittobi1992** [comment]
Hi @RoccoLoter,

in your example, the node weights in ``node_weights` sum up to 12, but your custom target weights only sum up to 9. Therefore, no feasible solution exists. If you change this, e.g. to 8 and 9, it should work. However, keep in mind that even if the sum of all custom target weights is larger than the weight of the hypergraph, no feasible solution may exist. For example, consider a hypergraph with three nodes and node weights 3, 3, and 1 and the maximum allowed weight for the first block is 5 and for the second block is 2. Then, there exists no feasible assignment of the nodes to the blocks that satisfy the custom target block weights. Thus, it is always a good idea to allow some leeway in the maximum allowed block weights to ensure that a feasible solution exists.
