### ISSUE TITLE
Proposal: Input validation

### ISSUE THREAD

**Issue by N-Maas** [kahypar/kahypar#166]
Both when providing a hMetis file or directly using the C interface it is easy to mess up the input hypergraph in some way (e.g., starting the indices in the hMetis file at 0, forgetting the sentinel when using the C interface, plain logic errors in input generation, ...). Looking at recent issues, it seems this happens regularly to some of our users.

Since invalid input most likely results in a segfault or even garbage output, I think it would be much better to validate the input and throw an explicit error. Of course, to be useful this needs to be mandatory or at most opt-out with a compile flag (opt-in would hardly be used). However, the runtime impact should be extremely small, so I don't think this is a problem.

If you agree this makes sense @SebastianSchlag I would volunteer to implement it in the next few weeks.

I think it would make sense to do a syntactic validation when reading the input file and verify the actual values when constructing the hypergraph. Then, the validation also works when using the C interface.
One design question is probably whether we want to treat fixable errors (e.g. duplicate pins) as a warning or a hard error.

**Comment by kittobi1992** [comment]
I think this is a very good idea, but keep in mind that this is also something that we want to have in Mt-KaHyPar. I wonder if its time to setup a tooling repository (e.g., kahypar-tools or kahypar-shared-resources) were we move all stuff to shared between KaHyPar and Mt-KaHyPar (e.g., the factories and some data structures). Ultimately, the idea is to remove the dependency to KaHyPar from Mt-KaHyPar to ensure that we do not use accidentally some files under GPL license. What do you think @N-Maas and @SebastianSchlag ?

**Comment by kittobi1992** [comment]
One additional comment to the validation feature: I think that this is not something that we want to enable per default as it could potentially impact performance. We could provide some additional library functions that validates hMetis files and adjacency arrays from users.

**Comment by SebastianSchlag** [comment]
That is a great idea @N-Maas. I actually wanted to do that for a long time but never found the time to do it.  I would really appreciate if you could do that.

> However, the runtime impact should be extremely small, so I don't think this is a problem.
I agree and would also be in favor of enabling it by default - just to be sure. We could have a flag to explicitly disable it. Maybe we could add an extra timer and report the running time in the final output - just for transparency.

**Comment by SebastianSchlag** [comment]
> One design question is probably whether we want to treat fixable errors (e.g. duplicate pins) as a warning or a hard error.

For duplicate pins, we actually already do that at the moment (at least when reading the hypergraph from a file):

https://github.com/kahypar/kahypar/blob/e53beae2d1030507d9e181ea85e77c119f747975/kahypar/io/hypergraph_io.h#L114-L117

It would be great if we could have that functionality for the interfaces as well.

**Comment by SebastianSchlag** [comment]
> I think this is a very good idea, but keep in mind that this is also something that we want to have in Mt-KaHyPar. I wonder if its time to setup a tooling repository (e.g., kahypar-tools or kahypar-shared-resources) were we move all stuff to shared between KaHyPar and Mt-KaHyPar (e.g., the factories and some data structures). Ultimately, the idea is to remove the dependency to KaHyPar from Mt-KaHyPar to ensure that we do not use accidentally some files under GPL license. What do you think @N-Maas and @SebastianSchlag ?

That could be worth a try but I guess this could be done independent (i.e., after) the input validation. 

One thing that might make sense is to already add the new code under MIT license so that we can easily re-use it in Mt-KaHyPar directly.

**Comment by N-Maas** [comment]
> One thing that might make sense is to already add the new code under MIT license so that we can easily re-use it in Mt-KaHyPar directly.

Yeah, I can add the code that verifies the data from the C interface/the parsed data as a new file with MIT license. However, I don't think I can separate checks that directly relate to the file parsing from the parsing itself. At least not without parsing the file twice, which I would rather avoid since that could add significant overhead.

Sanitizing the input is a bit harder in case of the C interface. To do this efficiently I probably need to adjust the hypergraph constructor. But that should be doable. I think the cases that should generate a warning are the following: duplicate pins, hyperedges with zero or one pins, hyperedges with weight zero (did I forget any?)

Overall, I will probably do the following:
- Adjust `hypergraph_io.h` so that any syntactic errors in the input file are reported
- Add a new utility which checks for semantic errors (invalid pins, nodes with weight 0, invalid index array) and warnings (as above), reporting those as well as pins/hyperedges which should be ignored during construction
- The utility is called after reading the hMetis file/when calling the C interface. It is enabled by default but can be disabled with a compile flag. If enabled, the running time for this step is reported
- Adjust the hypergraph constructor such that it ignores pins/hyperedges as reported by the utility

Also, I can add a compiler flag which promotes the warnings to errors (disabled by default).

**Comment by SebastianSchlag** [comment]
> > One thing that might make sense is to already add the new code under MIT license so that we can easily re-use it in Mt-KaHyPar directly.
> 
> Yeah, I can add the code that verifies the data from the C interface/the parsed data as a new file with MIT license. However, I don't think I can separate checks that directly relate to the file parsing from the parsing itself. At least not without parsing the file twice, which I would rather avoid since that could add significant overhead.
> 
> Sanitizing the input is a bit harder in case of the C interface. To do this efficiently I probably need to adjust the hypergraph constructor. But that should be doable. I think the cases that should generate a warning are the following: duplicate pins, hyperedges with zero or one pins, hyperedges with weight zero (did I forget any?)
> 
> Overall, I will probably do the following:
> 
> * Adjust `hypergraph_io.h` so that any syntactic errors in the input file are reported
> * Add a new utility which checks for semantic errors (invalid pins, nodes with weight 0, invalid index array) and warnings (as above), reporting those as well as pins/hyperedges which should be ignored during construction
> * The utility is called after reading the hMetis file/when calling the C interface. It is enabled by default but can be disabled with a compile flag. If enabled, the running time for this step is reported
> * Adjust the hypergraph constructor such that it ignores pins/hyperedges as reported by the utility
> 
> Also, I can add a compiler flag which promotes the warnings to errors (disabled by default).

That sounds great! 👍
