### ISSUE TITLE
questions about "Warning: Hyperedge with size 0 or 1"

### ISSUE THREAD

**Issue by jcmgray** [kahypar/kahypar#177]
I think only since the latest release of `kahypar` (1.3.4), I get this warning very regularly: 
```
Warning: Hyperedge with size 0 or 1
```
Just a couple of questions:
- I take this to mean that the edge only appears on 0 or 1 nodes and thus contributes nothing to connectivity? rather than e.g. the weight of the edge
- is there any way to suppress the warning? having 'dangling' indices is very common for tensor networks and while one could filter those out before supplying to kahypar its quite convenient to supply the hypergraph 'as is'.

**Comment by N-Maas** [comment]
> I take this to mean that the edge only appears on 0 or 1 nodes and thus contributes nothing to connectivity? rather than e.g. the weight of the edge

Yes, that is exactly right.

> is there any way to suppress the warning? having 'dangling' indices is very common for tensor networks and while one could filter those out before supplying to kahypar its quite convenient to supply the hypergraph 'as is'.

You can disable these checks with the `-DKAHYPAR_INPUT_VALIDATION=OFF` compile flag (see https://github.com/kahypar/kahypar#input-validation).

**Comment by SebastianSchlag** [comment]
> You can disable these checks with the -DKAHYPAR_INPUT_VALIDATION=OFF compile flag (see https://github.com/kahypar/kahypar#input-validation).

Unfortunately, this won't work for users that use our precompiled Python packages. Maybe we should look into also making input validation a normal config parameter?

**Comment by jcmgray** [comment]
For the moment I have simply added a layer that parses out such edges in `cotengra` before being supplied to `kahypar` so the warning is suppressed for users there.

I don't think anything is strictly required to change here then, but I suppose my subjective opinion is that a size 1 edge is still a valid hypergraph, even if inconsequential for partitioning!

**Comment by SebastianSchlag** [comment]
> As mentioned in the PR, this config parameter would either not work with the C interface or necessitate a breaking API change (since it needs to be already present at hypergaph construction).

Ah, right. I had forgotten about that.

> I don't think anything is strictly required to change here then, but I suppose my subjective opinion is that a size 1 edge is still a valid hypergraph, even if inconsequential for partitioning!

I tend to agree with this. We should probably change the error message to only report hyperedges of size zero.

**Comment by N-Maas** [comment]
It seems this is actually more common than assumed when implementing the warning. I've opened #195 to remove warnings for size 1 hyperedges

**Comment by SebastianSchlag** [comment]
Thanks! I'll update the python packages in the next couple of days.

**Comment by SebastianSchlag** [comment]
Updated the release and the python package to `v1.3.5` that includes all latest changes (including #195).
