### ISSUE TITLE
Make Errors: compilation terminated due to -Wfatal-errors.

### ISSUE THREAD

**Issue by kdtran07** [kahypar/kahypar#178]
Here is the list of errors when I ran `make` in \kahypar\build\python:

> compilation terminated due to -Wfatal-errors.
make[2]: *** [python\CMakeFiles\kahypar_python.dir\build.make:76: python/CMakeFiles/kahypar_python.dir/module.cpp.obj] Error 1
make[1]: *** [CMakeFiles\Makefile2:3649: python/CMakeFiles/kahypar_python.dir/all] Error 2
make: *** [Makefile:145: all] Error 2

I have g++ version 13.1.0 and cmake version 3.27.3. I also ran

`cmake .. -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=RELEASE -DKAHYPAR_PYTHON_INTERFACE=1 -DKAHYPAR_USE_MINIMAL_BOOST=ON`

in build before on Windows 10 for boost. The common 

> warning:

have the following flags:

> [-Wc++20-compat]

> [-Weffc++]

> [-Wdeprecated-declarations]

and

> error: 'uint16_t' in namespace 'std' does not name a type; did you mean 'wint_t'?

Thank you for your help in advance.

**Comment by SebastianSchlag** [comment]
Hi @kdtran07, 
sorry for the late reply. It looks like your issue got lost in my inbox. 

Could you try running `make` again and post the full output? It looks like your log message doesn't contain the actual error.
Maybe running `make -d` will give more detailed logs.

Alternatively, you could try using the [Windows Subsystem for Linux](https://learn.microsoft.com/en-us/windows/wsl/about) and try to build KaHyPar there.

**Comment by kdtran07** [comment]
Hi @SebastianSchlag,

Thank you for your reply; I meant to have this issue marked as resolved because I was able to make the .so file on a _Macbook_ to run in python.

It has been some weeks since I resolved this, so I cannot recall all of the errors. Here is what I did to have the `make` to work (with my best recollection):

1. Update cmake_minimum_required(VERSION **3.27**) in the following files:

- ~/kahypar/external_tools/googletest/CMakeLists.txt
- ~/kahypar/external_tools/googletest/googletest/CMakeLists.txt
- ~/kahypar/external_tools/googletest/googlemock/CMakeLists.txt

- ~/kahypar/python/pybind11/CMakeLists.txt 

2. Respectively, resolve std::iterator deprecation in NodeIDIterator in graph.h and GenericHypergraph in hypergraph.h

- ~/kahypar/kahypar/datastructure/graph.h
- ~/kahypar/kahypar/datastructure/hypergraph.h

using firebush's answer in [stackoverflow](https://stackoverflow.com/questions/43268146/why-is-stditerator-deprecated)

3. Resolve PyEval_InitThreads() deprecation in ~/kahypar/python/pybind11/include/pybind11/detail/internal.h by removing it and add in Py_Initialize() and Py_Finalize()

4. Put parentheses around `has_hypernode_weights ? static_cast<size_t>(num_hypernodes) : 0` in line 103 of

~/kahypar/kahypar/io/hypergraph_io.h




I have edited the following files but do not remember where:

- ~/kahypar/python/pybind11/include/pybind11/pybind11.h


I might miss other things as well... Thanks again for checking in.
