### ISSUE TITLE
Running kKaHyPar-E for the cut metric

### ISSUE THREAD

**Issue by utkuumur** [kahypar/kahypar#180]
I was wondering why there is no preset for the evolutionary algorithm for the cut metric. Is there something that obstructs this, or can I create a similar preset by looking at the differences between kKaHypaR and kKaHyPar-E for the connectivity metric? Also, if you have something to start with, that would be very helpful.

**Comment by SebastianSchlag** [comment]
Hey @utkuumur, 

thanks for reaching out. There's actually no particular reason for this. We mainly just focussed on the connectivity metric in the paper. I just added a corresponding config for cut-net in https://github.com/kahypar/kahypar/pull/181. By adding the evolutionary parameters to the cut-net config for `rKaHyPar`, you could even created an evolutionary version of rKaHyPar.

**Comment by utkuumur** [comment]
Thank you so much for creating the config so quickly!
