### ISSUE TITLE
Build failure due to kahypar_create_hypergraph_from_file test

### ISSUE THREAD

**Issue by grwlf** [kahypar/kahypar#184]
OS: Ubuntu 22.04.1 LTS  (need to say it is a Docker image)
Revision: c1efa28379c3c8d

cmake line:

` cmake .. -DCMAKE_BUILD_TYPE=RELEASE -DKAHYPAR_USE_MINIMAL_BOOST=ON  -DKAHYPAR_PYTHON_INTERFACE=ON -DCMAKE_CXX_FLAGS="-fPIC"
`

The error is:
```
[----------] 1 test from CorruptedHypergraphFile
[ RUN      ] CorruptedHypergraphFile.IsRejectedByInputValidation
/workspace/modules/kahypar/tests/interface/interface_test.cc:662: Failure
Death test: kahypar_create_hypergraph_from_file(filename.c_str(), num_blocks)
    Result: died but not with expected exit code:
            Terminated by signal 11 (core dumped)
Actual msg:
[  DEATH   ]
Segmentation fault (core dumped)
make[2]: *** [tests/interface/CMakeFiles/interface_test.dir/build.make:105: tests/interface/interface_test] Error 139
make[2]: *** Deleting file 'tests/interface/interface_test'
make[2]: Leaving directory '/workspace/modules/kahypar/_build'
make[1]: *** [CMakeFiles/Makefile2:2085: tests/interface/CMakeFiles/interface_test.dir/all] Error 2
make[1]: Leaving directory '/workspace/modules/kahypar/_build'
make: *** [Makefile:146: all] Error 2

```

UPD: Commenting this test makes build finish successfully.

**Comment by grwlf** [comment]
-fPIC was added due to https://github.com/kahypar/kahypar/issues/183

**Comment by grwlf** [comment]
Just a thought: does the name of a build folder matter? I named it _build rather than build

**Comment by SebastianSchlag** [comment]
Hey @grwlf , thanks for reaching out. 

> Just a thought: does the name of a build folder matter? I named it _build rather than build

The name of the build folder should actually not matter. 

> CorruptedHypergraphFile.IsRejectedByInputValidation

This test is relatively new. @N-Maas did we miss something in the test setup that could cause this?

**Comment by grwlf** [comment]
> The name of the build folder should actually not matter

Indeed, I already tried with just `build` with the same result.

**Comment by N-Maas** [comment]
> This test is relatively new. @N-Maas did we miss something in the test setup that could cause this?

Yes, it seems the tests fail if compiled with `-DKAHYPAR_INPUT_VALIDATION=OFF`. I have opened #188 to fix this.

**Comment by SebastianSchlag** [comment]
@grwlf Just double-checking: Did you have set `KAHYPAR_INPUT_VALIDATION` to `off`?
