### ISSUE TITLE
Can kahypar give the hyperedges those are cut after partition?

### ISSUE THREAD

**Issue by RoyIronGrey** [kahypar/kahypar#194]
e.x., when I execute the python/tests/test_kahypar.py, I can get the block of each node belonging. Can I get the hyperedges those are cut from any function. I coded a function to do that, but it is inefficient.
```
def get_cut_hyperedges(result, hyperedge_indices, hyperedge):
    cut_hyperedges = []
    for i in range(len(hyperedge_indices) - 1):
        start_idx = hyperedge_indices[i]
        end_idx = hyperedge_indices[i+1]
        hyperedge_nodes = hyperedge[start_idx:end_idx]
        part_set = set()
        for part_idx, part_nodes in enumerate(result):
            if any(node in part_nodes for node in hyperedge_nodes):
                part_set.add(part_idx)
        if len(part_set) > 1:
            cut_hyperedges.append(hyperedge[start_idx:end_idx])
    return cut_hyperedges

# test-case
hyperedge_indices = [0, 4, 6, 7, 10, 12, 13, 16, 18, 19, 22, 25, 29]
hyperedge = [2, 5, 9, 10, 4, 9, 3, 7, 9, 10, 6, 7, 2, 1, 3, 8, 2, 5, 7, 4, 9, 10, 1, 2, 3, 1, 2, 5, 8]
result = [[1, 2, 3, 5, 8, 12], [4, 6, 7, 9, 10, 11]]
cut_hyperedges = get_cut_hyperedges(result, hyperedge_indices, hyperedge)
print("Cut Hyperedges:", cut_hyperedges) 
```

**Comment by SebastianSchlag** [comment]
Hi @RoyIronGrey,
thanks for reaching out.

Yes, this is possible via:

```python
for e in hypergraph.edges():
	if hypergraph.connectivity(e) > 1:
		print (f"cut edge: {e}")
```

The entire interface available and (somewhat poorly) documented here: https://github.com/kahypar/kahypar/blob/master/python/module.cpp

**Comment by RoyIronGrey** [comment]
> Hi @RoyIronGrey, thanks for reaching out.
> 
> Yes, this is possible via:
> 
> ```python
> for e in hypergraph.edges():
> 	if hypergraph.connectivity(e) > 1:
> 		print (f"cut edge: {e}")
> ```
> 
> The entire interface available and (somewhat poorly) documented here: https://github.com/kahypar/kahypar/blob/master/python/module.cpp

Thanks for your reply. The `e in hypergraph.edges()` I got is a integer, but the hyperedge should include mutil nodes, right? I am a bit confused.

**Comment by N-Maas** [comment]
> Thanks for your reply. The `e in hypergraph.edges()` I got is a integer, but the hyperedge should include mutil nodes, right? I am a bit confused.

`hypergraph.edges()` returns the IDs of the hyperedges. You can retrieve the included nodes of the hyperedge (which are called the pins of the hyperedge) via `hypergraph.pins(e)`.

**Comment by RoyIronGrey** [comment]
> > Thanks for your reply. The `e in hypergraph.edges()` I got is a integer, but the hyperedge should include mutil nodes, right? I am a bit confused.
> 
> `hypergraph.edges()` returns the IDs of the hyperedges. You can retrieve the included nodes of the hyperedge (which are called the pins of the hyperedge) via `hypergraph.pins(e)`.

Thanks a lot!
