### ISSUE TITLE
Can KaHyPar be used to graph partitioning?

### ISSUE THREAD

**Issue by Fern-Parker** [kahypar/kahypar#197]
Can KaHyPar be used to graph partitioning  (i.e., the case of simple graph, an edge can connect no more than two vertexes)?  I know this problem is stupid, and I beg your pardon.

**Comment by SebastianSchlag** [comment]
Hi @Fern-Parker, 

>Can KaHyPar be used to graph partitioning (i.e., the case of simple graph, an edge can connect no more than two vertexes)?

Yes, it can. The only thing you have to do is to make sure your graph is stored in the [hMetis file format](http://glaros.dtc.umn.edu/gkhome/fetch/sw/hmetis/manual.pdf).

> I know this problem is stupid, and I beg your pardon.

Not at all. No worries. 🙂

**Comment by Fern-Parker** [comment]
Prof. Schlag, thank you so much for your kindness!
