### ISSUE TITLE
About the V-cycle design

### ISSUE THREAD

**Issue by chenmagi** [kahypar/kahypar#199]
Hello,

I've integrated Kahypar's V-cycle routine into my project and I'm seeing a good enhancement in hyper-cut. The paper mentions that "KaHyPar’s V-cycles confine contractions to blocks of the previous solution and utilize either the old or a newly computed solution as the initial partition." Could you provide further clarification on how the V-cycle contributes to improving the cut?

Best,

Magi

**Comment by larsgottesbueren** [comment]
Hi Magi,

The benefit of V-cycles is starting the local search with an already good partition but enabling optimization at macro and micro levels again by going through all the 'granularities' of coarsening. This allows revisiting some decisions and also diversifies the search space. Trying another initial partition falls under the same category.

Hope this helps.
Lars

**Comment by SebastianSchlag** [comment]
Hi @chenmagi, 

expanding on @larsgottesbueren's answer a bit: In the first iteration of the multi-level approach, we start with an unpartitioned hypergraph which is successively coarsened in the coarsening phase. The smallest/coarsest hypergraph is initially partitioned, and then the coarsening is undone and, at each level of the hierarchy, local search and flow algorithms try to refine the solution. One of the goals of the coarsening phase is to make sure that the coarser hypergraphs remain structurally similar to the input hypergraph. However, this is not really guaranteed - so some "unfortunate" contractions can actually obscure small cuts.

For example, assume the following graph, in which cutting the edge in the middle would give a perfectly balanced bipartition with a cut of 1:

```
 o         o
  \       /
   o-----o
  /       \
 o         o

```

If we contract this edge accidentally during the coarsening phase, this balanced cut does not exist anymore and we would have to cut 2 edges to get a slightly imbalanced partition:

```
    o   o
     \ /
      o
     / \
    o   o

```

A key difference between the _first_ iteration and subsequent V-cycles is the fact that the partition computed in the first iteration is used to guide the coarsening process: Restricting contractions to vertices that belong to the same block of the partition ensures that the computed cut of the input hypergraph does not get destroyed during the V-cycle coarsening phase. In some sense, this might prevent some "bad" contractions. Therefore, both the input hypergraph and the coarsest one will have the same cut/connectivity. The refinement phase then starts off with a good partition and can potentially find additional small improvements at different levels of 'granularities'  as @larsgottesbueren  described.

**Comment by chenmagi** [comment]
> Hi Magi,
> 
> The benefit of V-cycles is starting the local search with an already good partition but enabling optimization at macro and micro levels again by going through all the 'granularities' of coarsening. This allows revisiting some decisions and also diversifies the search space. Trying another initial partition falls under the same category.
> 
> Hope this helps. Lars

Hi Lars,

Thanks for your comment.

**Comment by chenmagi** [comment]
> Hi @chenmagi,
> 
> expanding on @larsgottesbueren's answer a bit: In the first iteration of the multi-level approach, we start with an unpartitioned hypergraph which is successively coarsened in the coarsening phase. The smallest/coarsest hypergraph is initially partitioned, and then the coarsening is undone and, at each level of the hierarchy, local search and flow algorithms try to refine the solution. One of the goals of the coarsening phase is to make sure that the coarser hypergraphs remain structurally similar to the input hypergraph. However, this is not really guaranteed - so some "unfortunate" contractions can actually obscure small cuts.
> 
> For example, assume the following graph, in which cutting the edge in the middle would give a perfectly balanced bipartition with a cut of 1:
> 
> ```
>  o         o
>   \       /
>    o-----o
>   /       \
>  o         o
> ```
> 
> If we contract this edge accidentally during the coarsening phase, this balanced cut does not exist anymore and we would have to cut 2 edges to get a slightly imbalanced partition:
> 
> ```
>     o   o
>      \ /
>       o
>      / \
>     o   o
> ```
> 
> A key difference between the _first_ iteration and subsequent V-cycles is the fact that the partition computed in the first iteration is used to guide the coarsening process: Restricting contractions to vertices that belong to the same block of the partition ensures that the computed cut of the input hypergraph does not get destroyed during the V-cycle coarsening phase. In some sense, this might prevent some "bad" contractions. Therefore, both the input hypergraph and the coarsest one will have the same cut/connectivity. The refinement phase then starts off with a good partition and can potentially find additional small improvements at different levels of 'granularities' as @larsgottesbueren described.

Thank you for the thorough breakdown. I've grasped the concept completely.
