### ISSUE TITLE
Can KaHyPar support zero vertex weight?

### ISSUE THREAD

**Issue by chenmagi** [kahypar/kahypar#202]
Hi,

 I noticed that the current version of KaHyPar fails when the hypergraph contains some vertices with zero weight. Is it possible to implement a solution to address this issue?

best,

Magi

**Comment by SebastianSchlag** [comment]
Hi @chenmagi,

sorry for the delayed response.

 I double-checked the code and it looks like we added the requirement to have non-zero vertex weights as part of our general input validation in https://github.com/kahypar/kahypar/pull/167. 
If you compile KaHyPar with cmake flag `KAHYPAR_INPUT_VALIDATION=OFF` you can bypass that check. 
In `RELEASE` mode, I was able to partition a weighted hypergraph with a couple of zero-weighted vertices. In `DEBUG` mode, this assertion got triggered: https://github.com/kahypar/kahypar/blob/875464be4c31681244a39bfeee1aaec42f6e14c8/kahypar/partition/refinement/2way_fm_refiner.h#L216-L223

Technically violating this assertion in the presence of vertices with weight zero might be fine. I'm not entirely sure though if we rely on non-zero vertex weights in other parts of the code. So it might make sense to sanity-check that partitions generated using the approach outlined above are actually valid.

@N-Maas @larsgottesbueren  @TobiasHeuer  Are you folks aware of anything that might break if we allow zero-weighted vertices?

**Comment by larsgottesbueren** [comment]
The only thing that came to mind is the heavy node penalty in heavy edge rating during coarsening. Div by zero is not nice, but that's an easy fix.

**Comment by larsgottesbueren** [comment]
PQ selection policies in IP? Also setting up max part weights and similar stuff might have some unexpected issues lurking

**Comment by N-Maas** [comment]
No, the requirement was not added in #167. Previous to the PR, the hypergraph parser already contained a check whether a node has weight zero and would abort if this was the case. #167 just moved the check to the generalized validation logic.

The original check was introduced with Commit dda46732c8 in May 2021. I don't know the reasoning. We added individual part weight support roughly at the same time, though this is probably unrelated.

**Comment by kittobi1992** [comment]
The question is if zero weight vertices really matters in the partition problem. For example, can we contract an zero weight vertex onto one of its neighbours, partition the hypergraph, revert the contraction, and then still prove some optimality? Any idea on that?

Basically, we can assign a zero weight vertex to any partition after partitioning for free. Can we do some greedy heuristic after partitioning to assign them?

**Comment by N-Maas** [comment]
> Basically, we can assign a zero weight vertex to any partition after partitioning for free. Can we do some greedy heuristic after partitioning to assign them?

At least for bipartitioning, I'm pretty sure that assigning the zero weight vertices to a fixed partition is equivalent to solving a flow problem on the zero weight subgraph (just contract the blocks of non-zero vertices into single nodes, which are then source and sink). So it's doable, but a greedy approach is not sufficient for the general case.

However, since the cost of assigning the zero weight vertices depends on the partition of the remaining vertices, this does not allow to ignore them during partitioning. Heuristics like contraction onto a neighbor also won't allow optimality - you might choose the wrong neighbor, e.g., which is in a different block than all the other neighbors.

**Comment by chenmagi** [comment]
Hi,

@SebastianSchlag @N-Maas @larsgottesbueren @kittobi1992 Thank you for your comments. I rebuilt KaHyPar in RELEASE mode, and it now handles graphs with some zero-vertex weights.

Best,

Magi

**Comment by gjz010** [comment]
Hi,
I came across the problem when I'm working on reproducing some results on distributed quantum circuit compilation (DQC problem), specifically:
- [Automated distribution of quantum circuits via hypergraph partitioning](https://arxiv.org/abs/1811.10972)
- [pytket-dqc](https://github.com/CQCL/pytket-dqc)

> The question is if zero weight vertices really matters in the partition problem. For example, can we contract an zero weight vertex onto one of its neighbours, partition the hypergraph, revert the contraction, and then still prove some optimality? Any idea on that?
> 
> Basically, we can assign a zero weight vertex to any partition after partitioning for free. Can we do some greedy heuristic after partitioning to assign them?

I'm no expert in hypergraph partitioning problems, but as far as I know, zero-weight vertices play a very intuitive and important role in hypergraph approaches for distributed quantum circuit compilation:

- One-weight vertices correspond to qubits in the circuit, and zero-weight vertices correspond to two-qubit (CZ) gates in the circuit. 
  - This is from the problem assumption that we want to assign qubits nodes balanced while reducing communication as much as possible, but we don't care about how CZ gates are load-balanced.
- The partitioning result yields the circuit's execution strategy: the partition where the zero-weight vertex lands corresponds to which node this CZ gate will be executed (i.e., the other operand of the CZ gate will be sent to this node).
  - Every cut over a hyperedge indicates consuming 1 EPR pair for communication.
- There are "assignment of neighbours" that are better than others. For example, a qubit can be sent to another device to enable execution of many CZ gates. This is referred to as ["burst communication"](https://arxiv.org/abs/2207.11674) in some literature.
  - This potential of burst communication is modeled by hyperedges, i.e. as @N-Maas said: 
> Heuristics like contraction onto a neighbor also won't allow optimality - you might choose the wrong neighbor, e.g., which is in a different block than all the other neighbors.

Again, I'm no expert in graph partitioning, but I guess finding a good heuristic for assigning a zero-weight vertex to a neighbor is no easier than identifying and assigning burst communications in a quantum circuit. Moreover, I hope KaHyPar could provide an option to allow zero-weight vertices, as there are already many works on the DQC problem that use KaHyPar for good initial partitioning.

Hope these information will be helpful.

Best,
gjz010
