### ISSUE TITLE
deterministic results when using profile "cut_rKaHyPar_sea20.ini"

### ISSUE THREAD

**Issue by chenmagi** [kahypar/kahypar#205]
Hi,

  When I used the parameters k=2, e=0.04, and m=recursive along with the profile "cut_rKaHyPar_sea20.ini," the results appeared to be deterministic, yielding the same cut size after 10 trials. Could you please provide some insight into this situation? I have attached the tested hypergraph 'adaptec1.hgr.'
[adaptec1.hgr.zip](https://github.com/user-attachments/files/16048863/adaptec1.hgr.zip)

Best,

Magi

**Comment by kittobi1992** [comment]
Hi @chenmagi,

if you want different results for different trials, you should set individual seed values for each trial.

Best,
@kittobi1992

**Comment by SebastianSchlag** [comment]
Hi @chenmagi ,

your observation is correct. By default, all the configs set the `seed` parameter to `-1` - so repeated executions will give the same results. You can use the `--seed` command line parameter to set a different seed value. The C interface provides [`kahypar_set_seed`](https://github.com/kahypar/kahypar/blob/875464be4c31681244a39bfeee1aaec42f6e14c8/lib/libkahypar.cc#L63-L66). The Python interface provides [`setSeed`](https://github.com/kahypar/kahypar/blob/875464be4c31681244a39bfeee1aaec42f6e14c8/python/module.cpp#L276).

**Comment by chenmagi** [comment]
@kittobi1992 @SebastianSchlag Thanks for the comment.
