### ISSUE TITLE
Handling Multi-Dimensional Vertex Weights in KaHyPar

### ISSUE THREAD

**Issue by lygwzy89** [kahypar/kahypar#206]
I have noticed that KaHyPar currently only handles hypergraphs with one-dimensional vertex weights. I would like to know if KaHyPar has the capability to handle hypergraphs with multi-dimensional vertex weights. If not, are there any workarounds or alternative approaches that I can use to address this issue?	Thank you for your time and consideration.

**Comment by N-Maas** [comment]
Hi @lygwzy89,

KaHyPar is unfortunately not able to handle multi-dimensional weights. We are currently working on support for multi-constraint partitioning (which is another name for the same thing) in [Mt-KaHyPar](https://github.com/kahypar/mt-kahypar). However, this is extremely experimental at the moment and might still require something like a year until it is available in master. We could give you access to the experimental state, but it is not super usable yet (e.g. it requires defining the dimension at compile time and has no good multi-constraint coarsening algorithm).

In the meantime, it would probably be easier to use [PaToH](https://faculty.cc.gatech.edu/~umit/software.html). PaToH is, as far as I know, currently the only hypergraph partitioner with multi-constraint support. Note that the support is only available for the library interface and not for the CLI tool (see the _nconst parameter in the [manual](https://faculty.cc.gatech.edu/~umit/PaToH/manual.pdf)).

If you don't mind, could you share your use case for multi-dimensional weights with us? It would be helpful to know more about applications for this.

**Comment by lygwzy89** [comment]
> Hi @lygwzy89,
> 
> KaHyPar is unfortunately not able to handle multi-dimensional weights. We are currently working on support for multi-constraint partitioning (which is another name for the same thing) in [Mt-KaHyPar](https://github.com/kahypar/mt-kahypar). However, this is extremely experimental at the moment and might still require something like a year until it is available in master. We could give you access to the experimental state, but it is not super usable yet (e.g. it requires defining the dimension at compile time and has no good multi-constraint coarsening algorithm).
> 
> In the meantime, it would probably be easier to use [PaToH](https://faculty.cc.gatech.edu/~umit/software.html). PaToH is, as far as I know, currently the only hypergraph partitioner with multi-constraint support. Note that the support is only available for the library interface and not for the CLI tool (see the _nconst parameter in the [manual](https://faculty.cc.gatech.edu/~umit/PaToH/manual.pdf)).
> 
> If you don't mind, could you share your use case for multi-dimensional weights with us? It would be helpful to know more about applications for this.

Thank you for your reply. If kahypar does not support handling such weights, I may temporarily convert the multi-dimensional weights to one-dimensional weights by weight merging.

I need to handle multi-dimensional weights because I want to partition the FPGA netlist, and the components in the FPGA netlist are of different types, which means the weights are multi-dimensional.

Thanks again for your help!
