### ISSUE TITLE
How does KaHyPar represent the actual connectivity

### ISSUE THREAD

**Issue by lygwzy89** [kahypar/kahypar#207]
Hi,

I would like to use KaHyPar to partition circuit netlists. However, I have a question about how KaHyPar represents the actual connectivity of the netlist elements. (I could not find anything like an adjacency list or adjacency matrix in the code.)

For example, consider three elements 0, 1, and 2. Element 0 connects to elements 1 and 2, and element 1 connects to element 2. How would this connectivity be represented in KaHyPar?Would this connectivity result in two hyperedges, {0, 1, 2} and {1, 2}?

Additionally, if the connection from element 0 to element 1 has a weight of 2, while the other connections have a weight of 1, how would these weights be represented and handled in the hyperedges?	

Thank you for your time and consideration.

**Comment by SebastianSchlag** [comment]
Hi @lygwzy89, 

Sorry for the delayed response. Since you closed the issue, I presume you figured it out? 🙂 Please let us know if anything is still unclear.
