### ISSUE TITLE
One of the partitions has a negative weight in _part_info

### ISSUE THREAD

**Issue by lygwzy89** [kahypar/kahypar#208]
I am using KaHyPar for partitioning and encountered an error:
[2way_fm_refiner.h:439:updateNeighbours]: Assertion `(!_pq.empty(1) && _hg.partWeight(1) < max_allowed_part_weights[1] ? _pq.isEnabled(1) : !_pq.isEnabled(1))` failed: 1 = 1 

I observed that _hg.partWeight() indicates a negative weight for one part in _part_info (although the sum of weights for all parts still equals the total weight):"
_part_info[0].weight:-1554255480
_part_info[1].weight:1898982888
_part_info[2].weight:0
What is the reason for this and how can it be fixed?
thanks

Information about my case:
cmd: -h hypergraph_metis_file.hgr", "-k 3", "-e 0.08", "-o cut", "-m direct", "-p /kahypar-master/config/cut_kKaHyPar-E_sea20.ini
hypergraph inf:
    node:1082
    edge:1055
    pins:3238
    weight:344727408

CALL STACK:
libc.so.6!raise (Unknown Source:0)
libc.so.6!abort (Unknown Source:0)
kahypar::TwoWayFMRefiner<kahypar::NumberOfFruitlessMovesStopsSearch, kahypar::CutDecreasedOrInfeasibleImbalanceDecreased>::updateNeighbours(kahypar::TwoWayFMRefiner<kahypar::NumberOfFruitlessMovesStopsSearch, kahypar::CutDecreasedOrInfeasibleImbalanceDecreased> * const this, const kahypar::HypernodeID moved_hn, const kahypar::PartitionID from_part, const kahypar::PartitionID to_part, const kahypar::TwoWayFMRefiner<kahypar::NumberOfFruitlessMovesStopsSearch, kahypar::CutDecreasedOrInfeasibleImbalanceDecreased>::HypernodeWeightArray & max_allowed_part_weights) (/kahypar-master/kahypar/partition/refinement/2way_fm_refiner.h:439)
kahypar::TwoWayFMRefiner<kahypar::NumberOfFruitlessMovesStopsSearch, kahypar::CutDecreasedOrInfeasibleImbalanceDecreased>::refineImpl(kahypar::TwoWayFMRefiner<kahypar::NumberOfFruitlessMovesStopsSearch, kahypar::CutDecreasedOrInfeasibleImbalanceDecreased> * const this, std::vector<unsigned int, std::allocator<unsigned int> > & refinement_nodes, const kahypar::TwoWayFMRefiner<kahypar::NumberOfFruitlessMovesStopsSearch, kahypar::CutDecreasedOrInfeasibleImbalanceDecreased>::HypernodeWeightArray & max_allowed_part_weights, const kahypar::UncontractionGainChanges & changes, kahypar::Metrics & best_metrics) (/kahypar-master/kahypar/partition/refinement/2way_fm_refiner.h:283)
kahypar::IRefiner::refine(kahypar::IRefiner * const this, std::vector<unsigned int, std::allocator<unsigned int> > & refinement_nodes, const std::array<int, 2> & max_allowed_part_weights, const kahypar::UncontractionGainChanges & uncontraction_changes, kahypar::Metrics & best_metrics) (/kahypar-master/kahypar/partition/refinement/i_refiner.h:54)
kahypar::InitialPartitionerBase<kahypar::GreedyHypergraphGrowingInitialPartitioner<kahypar::BFSStartNodeSelectionPolicy<true>, kahypar::FMGainComputationPolicy, kahypar::RoundRobinQueueSelectionPolicy> >::performFMRefinement(kahypar::InitialPartitionerBase<kahypar::GreedyHypergraphGrowingInitialPartitioner<kahypar::BFSStartNodeSelectionPolicy<true>, kahypar::FMGainComputationPolicy, kahypar::RoundRobinQueueSelectionPolicy> > * const this) (/kahypar-master/kahypar/partition/initial_partitioning/initial_partitioner_base.h:231)
kahypar::GreedyHypergraphGrowingInitialPartitioner<kahypar::BFSStartNodeSelectionPolicy<true>, kahypar::FMGainComputationPolicy, kahypar::RoundRobinQueueSelectionPolicy>::initialPartition(kahypar::GreedyHypergraphGrowingInitialPartitioner<kahypar::BFSStartNodeSelectionPolicy<true>, kahypar::FMGainComputationPolicy, kahypar::RoundRobinQueueSelectionPolicy> * const this) (/kahypar-master/kahypar/partition/initial_partitioning/greedy_hypergraph_growing_initial_partitioner.h:269)
kahypar::InitialPartitionerBase<kahypar::GreedyHypergraphGrowingInitialPartitioner<kahypar::BFSStartNodeSelectionPolicy<true>, kahypar::FMGainComputationPolicy, kahypar::RoundRobinQueueSelectionPolicy> >::multipleRunsInitialPartitioning(kahypar::InitialPartitionerBase<kahypar::GreedyHypergraphGrowingInitialPartitioner<kahypar::BFSStartNodeSelectionPolicy<true>, kahypar::FMGainComputationPolicy, kahypar::RoundRobinQueueSelectionPolicy> > * const this) (/kahypar-master/kahypar/partition/initial_partitioning/initial_partitioner_base.h:116)
kahypar::GreedyHypergraphGrowingInitialPartitioner<kahypar::BFSStartNodeSelectionPolicy<true>, kahypar::FMGainComputationPolicy, kahypar::RoundRobinQueueSelectionPolicy>::partitionImpl(kahypar::GreedyHypergraphGrowingInitialPartitioner<kahypar::BFSStartNodeSelectionPolicy<true>, kahypar::FMGainComputationPolicy, kahypar::RoundRobinQueueSelectionPolicy> * const this) (/kahypar-master/kahypar/partition/initial_partitioning/greedy_hypergraph_growing_initial_partitioner.h:99)
kahypar::IInitialPartitioner::partition(kahypar::IInitialPartitioner * const this) (/kahypar-master/kahypar/partition/initial_partitioning/i_initial_partitioner.h:38)
kahypar::PoolInitialPartitioner::initialPartition(kahypar::PoolInitialPartitioner * const this) (/kahypar-master/kahypar/partition/initial_partitioning/pool_initial_partitioner.h:138)
kahypar::InitialPartitionerBase<kahypar::PoolInitialPartitioner>::multipleRunsInitialPartitioning(kahypar::InitialPartitionerBase<kahypar::PoolInitialPartitioner> * const this) (/kahypar-master/kahypar/partition/initial_partitioning/initial_partitioner_base.h:116)
kahypar::PoolInitialPartitioner::partitionImpl(kahypar::PoolInitialPartitioner * const this) (/kahypar-master/kahypar/partition/initial_partitioning/pool_initial_partitioner.h:109)
kahypar::IInitialPartitioner::partition(kahypar::IInitialPartitioner * const this) (/kahypar-master/kahypar/partition/initial_partitioning/i_initial_partitioner.h:38)
kahypar::initial::partition(kahypar::Hypergraph & hg, const kahypar::Context & context) (/kahypar-master/kahypar/partition/initial_partition.h:165)
kahypar::multilevel::partition(kahypar::Hypergraph & hypergraph, kahypar::ICoarsener & coarsener, kahypar::IRefiner & refiner, const kahypar::Context & context) (/kahypar-master/kahypar/partition/multilevel.h:64)
kahypar::multilevel::partitionRepeatedOnInfeasible(kahypar::Hypergraph & hypergraph, const kahypar::Context & context, kahypar::Context::PartitioningStats & stats, const kahypar::bin_packing::BalancingLevel level, const std::vector<int, std::allocator<int> > max_bin_weights, const bool repeat) (/kahypar-master/kahypar/partition/multilevel.h:163)
kahypar::recursive_bisection::partition(kahypar::Hypergraph & input_hypergraph, const kahypar::Context & original_context) (/kahypar-master/kahypar/partition/recursive_bisection.h:391)
kahypar::partition::partition(kahypar::Hypergraph & hypergraph, const kahypar::Context & context) (/kahypar-master/kahypar/partition/partitioner.h:77)
kahypar::initial::partition(kahypar::Hypergraph & hg, const kahypar::Context & context) (/kahypar-master/kahypar/partition/initial_partition.h:168)
kahypar::multilevel::partition(kahypar::Hypergraph & hypergraph, kahypar::ICoarsener & coarsener, kahypar::IRefiner & refiner, const kahypar::Context & context) (/kahypar-master/kahypar/partition/multilevel.h:64)
kahypar::direct_kway::partition(kahypar::Hypergraph & hypergraph, const kahypar::Context & context) (/kahypar-master/kahypar/partition/direct_kway.h:83)
kahypar::partition::partition(kahypar::Hypergraph & hypergraph, const kahypar::Context & context) (/kahypar-master/kahypar/partition/partitioner.h:80)
kahypar::Partitioner::partition(kahypar::Partitioner * const this, kahypar::Hypergraph & hypergraph, kahypar::Context & context) (/kahypar-master/kahypar/partition/partitioner.h:342)
kahypar::Population::generateIndividual(kahypar::Population * const this, kahypar::Hypergraph & hg, kahypar::Context & context) (/kahypar-master/kahypar/partition/evolutionary/population.h:99)
kahypar::EvoPartitioner::generateInitialPopulation(kahypar::EvoPartitioner * const this, kahypar::Hypergraph & hg, kahypar::Context & context) (/kahypar-master/kahypar/partition/evo_partitioner.h:99)
kahypar::EvoPartitioner::partition(kahypar::EvoPartitioner * const this, kahypar::Hypergraph & hg, kahypar::Context & context) (/kahypar-master/kahypar/partition/evo_partitioner.h:55)
kahypar::PartitionerFacade::performEvolutionaryPartitioning(kahypar::PartitionerFacade * const this, kahypar::Hypergraph & hypergraph, kahypar::Context & context) (/kahypar-master/kahypar/partitioner_facade.h:170)
kahypar::PartitionerFacade::performPartitioning(kahypar::PartitionerFacade * const this, kahypar::Hypergraph & hypergraph, kahypar::Context & context) (/kahypar-master/kahypar/partitioner_facade.h:186)
kahypar::PartitionerFacade::partition(kahypar::PartitionerFacade * const this, kahypar::Hypergraph & hypergraph, kahypar::Context & context) (/kahypar-master/kahypar/partitioner_facade.h:60)
main(int argc, char ** argv) (/kahypar-master/kahypar/application/kahypar.cc:50)

**Comment by SebastianSchlag** [comment]
Two things come to my mind:
- Your hypergraph has very large node weights and the weights in on block of the partition overflow an `int32_t`. If that is the case, you can change the definition of `HypernodeWeight` from `int32_t` to `int64_t` in the `external_tools/kahypar-shared-resources/kahypar-resources/definitions.h` file.
- Something with the hypergraph itself is off.

In case the former doesn't work: Could you provide us with your hypergraph so that we can try to reproduce this locally?

**Comment by lygwzy89** [comment]
> Two things come to my mind:
> 
> * Your hypergraph has very large node weights and the weights in on block of the partition overflow an `int32_t`. If that is the case, you can change the definition of `HypernodeWeight` from `int32_t` to `int64_t` in the `external_tools/kahypar-shared-resources/kahypar-resources/definitions.h` file.
> * Something with the hypergraph itself is off.
> 
> In case the former doesn't work: Could you provide us with your hypergraph so that we can try to reproduce this locally?

After reducing the overall weight, the problem was resolved. Thank you for your advice.
