### ISSUE TITLE
python 3.12 pypi build

### ISSUE THREAD

**Issue by jcmgray** [kahypar/kahypar#210]
This is just a gentle enquiry about (/ request for), a cpython 3.12 kahypar pypi build.

I haven't looked into building it myself yet, so not aware if anything needs to be updated - as there was for py311 (#163).

**Comment by SebastianSchlag** [comment]
Hey @jcmgray,

thanks for the enquiry. Let me take a look to see if I can build it. :)

**Comment by SebastianSchlag** [comment]
✅ 

<img width="808" alt="Screenshot 2024-10-11 at 11 22 23 PM" src="https://github.com/user-attachments/assets/0b1f066c-b577-430d-8561-1ba0cbd298f2">

**Comment by jcmgray** [comment]
Beautiful, thanks!

**Comment by garrison** [comment]
macOS wheels still only go up to Python 3.11.

**Comment by SebastianSchlag** [comment]
@garrison Indeed. Building those is still on my list. I'll try to do it in the next couple of days.

**Comment by SebastianSchlag** [comment]
Hey @garrison,

just wanted to let you know that I just uploaded macOS wheels for 3.12 and 3.13:
https://pypi.org/project/kahypar/1.3.5/#files

**Comment by garrison** [comment]
> Hey @garrison,
> 
> just wanted to let you know that I just uploaded macOS wheels for 3.12 and 3.13: https://pypi.org/project/kahypar/1.3.5/#files

Great -- thank you!  And thank you for providing an update here.
