### ISSUE TITLE
Compilation failure：CMakeFiles/Makefile2:2022: tests/io/CMakeFiles/hypergraph_io_test.dir/all

### ISSUE THREAD

**Issue by chfissogoodman** [kahypar/kahypar#211]
I have the following problem when compiling. After reviewing the past issue, the method in it is still invalid. How should I solve it?Looking forward to hearing from you. Thank you！
 
  Segmentation fault (core dumped)
make[2]: *** [tests/io/CMakeFiles/hypergraph_io_test.dir/build.make:102: tests/io/hypergraph_io_test] Error 139
make[2]: *** Deleting file 'tests/io/hypergraph_io_test'
make[1]: *** [CMakeFiles/Makefile2:2022: tests/io/CMakeFiles/hypergraph_io_test.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

**Comment by SebastianSchlag** [comment]
Hey @chfissogoodman,
thanks for reaching out. What OS and compiler are you using?

Does `make KaHyPar` work or does that fail as well?

**Comment by chfissogoodman** [comment]
I am now having problems with “Ubuntu 24.04 LTS, gcc13” on the server, after I finished executing: cmake... -DCMAKE_BUILD_TYPE= RELEASE-DKAHYPAR_USE_MINIMAL_BOOST =ON After executing make, the above error occurs at 30% of the process. I do not have root privileges on the server, please tell me how to solve the problem, because I did not have this problem when compiling on a personal computer (Ubuntu 22.03). Thank you very much!

**Comment by N-Maas** [comment]
> I am now having problems with “Ubuntu 24.04 LTS, gcc13” on the server, after I finished executing: cmake... -DCMAKE_BUILD_TYPE= RELEASE-DKAHYPAR_USE_MINIMAL_BOOST =ON After executing make, the above error occurs at 30% of the process. I do not have root privileges on the server, please tell me how to solve the problem, because I did not have this problem when compiling on a personal computer (Ubuntu 22.03). Thank you very much!

Could you try using the command `make KaHyPar` for the build as suggested by Sebastian, @chfissogoodman?

**Comment by chfissogoodman** [comment]
Thank you very much. Now build is successful!
