### ISSUE TITLE
Symbol not found: __PyThreadState_Current

### ISSUE THREAD

**Issue by aneksteind** [kahypar/kahypar#58]
Hello, I'm attempting to use the kahypar backend in the cotengra library. In an attempt to run their Sycamore depth 12 example, I've run into the following exception:

```
Traceback (most recent call last):
  File "test_cotengra.py", line 40, in <module>
    info = tn.contract(all, optimize=opt, get='path-info', output_inds=[])
  File "/Users/david/Develop/cotengra/tensor/lib/python3.7/site-packages/quimb/tensor/tensor_core.py", line 3141, in contract
    return tensor_contract(*self, **opts)
  File "/Users/david/Develop/cotengra/tensor/lib/python3.7/site-packages/quimb/tensor/tensor_core.py", line 315, in tensor_contract
    path_info = get_contraction(eq, *ops, path=True, **contract_opts)
  File "/Users/david/Develop/cotengra/tensor/lib/python3.7/site-packages/quimb/tensor/tensor_core.py", line 110, in get_contraction
    return fn(eq, *shapes, **kwargs)
  File "/Users/david/Develop/cotengra/tensor/lib/python3.7/site-packages/quimb/tensor/tensor_core.py", line 78, in _get_contract_path
    return oe.contract_path(eq, *shapes, shapes=True, **kwargs)[1]
  File "/Users/david/Develop/cotengra/tensor/lib/python3.7/site-packages/opt_einsum/contract.py", line 259, in contract_path
    path = path_type(input_sets, output_set, dimension_dict, memory_arg)
  File "/Users/david/Develop/cotengra/tensor/lib/python3.7/site-packages/cotengra/hyper.py", line 347, in __call__
    for trial in trials:
  File "/Users/david/Develop/cotengra/tensor/lib/python3.7/site-packages/tqdm/std.py", line 1129, in __iter__
    for obj in iterable:
  File "/Users/david/Develop/cotengra/tensor/lib/python3.7/site-packages/cotengra/hyper.py", line 312, in _gen_results_parallel
    yield self.get_and_report_next_future()
  File "/Users/david/Develop/cotengra/tensor/lib/python3.7/site-packages/cotengra/hyper.py", line 296, in get_and_report_next_future
    trial = future.result()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
ImportError: dlopen(/Users/david/Develop/cotengra/tensor/lib/python3.7/site-packages/kahypar.cpython-37m-darwin.so, 2): Symbol not found: __PyThreadState_Current
  Referenced from: /Users/david/Develop/cotengra/tensor/lib/python3.7/site-packages/kahypar.cpython-37m-darwin.so
  Expected in: flat namespace
 in /Users/david/Develop/cotengra/tensor/lib/python3.7/site-packages/kahypar.cpython-37m-darwin.so
```

Helpful info:
OS: macOS Catalina
$PYTHONPATH: /Users/david/Library/Python/3.7/lib/python

I've tried changing my environment variables and editing the CMake of kahypar such that
`CC=clang`, `CXX=clang++` and, as a sanity check, to `CC=gcc`, `CXX=g++` -- taking care to uninstall and reinstall the kahypar python bindings with pip each time.

Any insight would be much appreciated.

**Comment by SebastianSchlag** [comment]
Hi,
Thank you for reaching out.

Could you please try to build and install the KaHyPar python interface as described in our readme (https://github.com/kahypar/kahypar#the-python-interface) and check whether you can get the example running on your system? This way, we could check whether this is a config problem on your system or a problem with the pip binaries.

Did you also ask the CoTenGra folks for help? I'm not sure how they integrated KaHyPar into the project.

**Comment by aneksteind** [comment]
Hi, thank you for the reply.

I followed those instructions with the same error:

```
ImportError: dlopen(/Users/david/Library/Python/3.7/lib/python/site-packages/kahypar.so, 2): Symbol not found: __PyThreadState_Current
  Referenced from: /Users/david/Library/Python/3.7/lib/python/site-packages/kahypar.so
  Expected in: flat namespace
 in /Users/david/Library/Python/3.7/lib/python/site-packages/kahypar.so
```

with the updated .so file following those instructions. I have [reached out](https://github.com/jcmgray/cotengra/issues/4) to the contengra folks, they're only using the pip dependency.

**Comment by aneksteind** [comment]
FWIW I was able to get this working on Ubuntu

**Comment by SebastianSchlag** [comment]
When running cmake, can you verify whether or not `-- Found PythonInterp:` and `-- Found PythonLibs:` output the correct paths for your python installation?

**Comment by aneksteind** [comment]
I think you're right, PyBind seems to think that my PythonLibs is /usr/lib/python2.7 when I am using python3. Is this something I can pass to the kahypar `setup.py` directly, or do you recommend trying to pass it to cmake directly

**Comment by aneksteind** [comment]
The following worked for me:

```bash
cmake -DPYTHON_EXECUTABLE:FILEPATH=python3 ..

make

# copy resulting .so to appropriate site_packages (in this case my virtual environment)
cp python/kahypar.cpython-37m-darwin.so kahypar_env/lib/python3.7/site-packages/
```

**Comment by SebastianSchlag** [comment]
That is great news! Thanks for the update.

I'm not sure what causes the problems with the PyPi installs. The pypi packages are build using centOS docker images (https://github.com/pypa/manylinux) - maybe that approach does not work well for macOS. I've just rebuild the binaries using the latest `manylinux2014` image: https://pypi.org/project/kahypar/1.1.2/

**Comment by SebastianSchlag** [comment]
> That is great news! Thanks for the update.
> 
> I'm not sure what causes the problems with the PyPi installs. The pypi packages are build using centOS docker images (https://github.com/pypa/manylinux) - maybe that approach does not work well for macOS. I've just rebuild and updated the binaries using the latest `manylinux2014` image: https://pypi.org/project/kahypar/1.1.2/

@aneksteind Does the new binary work for you?

**Comment by aneksteind** [comment]
It does not, my pip install skips over the versions you have on pypi because there are none with wheel tags pip on macos supports:

```
Skipping link: none of the wheel's tags match: cp37-cp37m-manylinux2014_x86_64: https://files.pythonhosted.org/packages/47/e6/90a8ab519b09bcbd5ee7743520c78840131aada865c9217d1942805e7a6a/kahypar-1.1.2-cp37-cp37m-manylinux2014_x86_64.whl#sha256=1918bf7376dac29e4da0c150ca180748be7d726e4c4c060cde406300d36b0706 (from https://pypi.org/simple/kahypar/)
```

**Comment by SebastianSchlag** [comment]
Hm, this is indeed strange. What version of pip are you currently using?

I had to build the binaries using a newer manylinux image, because the latest flow-based refinement code in KaHyPar needs a more recent gcc than what is available in the old image that was used to compile the v 1.0 binaries.

**Comment by aneksteind** [comment]
I'm not sure it's strange; manylinux is meant to build wheels for linux distributions, not macOS. And it seems that the totality of your wheels post-kahypar-1.0 are built with manylinux. You may just need to build wheels for other OS's you'd like to support via pypi. This is the reason that when I build from source it works out fine.

For the record, I tried with pip==20.1 and pip==19.3.1

**Comment by SebastianSchlag** [comment]
Even those of kahypar-1.0 were built with manylinux - only with the older version (i.e., `manylinux2010`). I'll try to find a way to also build dedicated macOS versions.

**Comment by aneksteind** [comment]
Ah, I can see how it's strange then. The wheel that 1.0 came packaged with that worked on macOS was `kahypar-1.0-cp37-cp37m-macosx_10_14_x86_64.whl`, for what that's worth. Thanks for looking into this!

**Comment by SebastianSchlag** [comment]
I managed to build some wheels for macos using `cibuildwheel`: https://pypi.org/project/kahypar/1.1.2/ 

Could you please check whether those work for you?

**Comment by aneksteind** [comment]
The wheel is found now: 
```
Collecting kahypar
  Using cached https://files.pythonhosted.org/packages/ad/a4/6ef67dd57be2371d6bb35eaafa37f03657d207c5e71736c8c759906371c9/kahypar-1.1.2-cp37-cp37m-macosx_10_9_x86_64.whl
Installing collected packages: kahypar
Successfully installed kahypar-1.1.2
```
And the python example you have on the homepage now works after:

```
brew install boost
brew install boost-python3
```

The boost I had in `/usr/local/lib` was where boost was expected to be:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/Users/david/Library/Python/3.7/lib/python/site-packages/kahypar.cpython-37m-darwin.so, 2): Library not loaded: /usr/local/opt/boost/lib/libboost_program_options-mt.dylib
  Referenced from: /Users/david/Library/Python/3.7/lib/python/site-packages/kahypar.cpython-37m-darwin.so
  Reason: image not found
```
after installing boost from source, but installing from homebrew seems to have resolved it.

**Comment by SebastianSchlag** [comment]
Perfect! Thank you very much for pointing out the issue and for helping to resolve it.
