### ISSUE TITLE
Verbosity Level of KaHyPar

### ISSUE THREAD

**Issue by romainwallon** [kahypar/kahypar#62]
Hi,

I am currently working on a [Java interface for KaHyPar](https://github.com/crillab/jkahypar), and I was wondering whether it were possible to reduce the verbosity of KaHyPar.

Indeed, in its most recent version, KaHyPar outputs many statistics, and I would like to turn them off.
However, I did not find a way to do so (without editing the source).

My main purpose with this Java implementation is to use KaHyPar as a library in another software, which requires to make many calls to the hypergraph partitioner.
Outputing so many statistics would make the invokation too slow in this context.

Is there any option for programmatically disabling this output?

Best regards,
Romain Wallon

**Comment by SebastianSchlag** [comment]
Hi Romain,

thanks for reaching out! 

You can suppress KaHyPars output completely be setting `context.partition.quiet_mode=true`  or adding `quiet_mode=true` to your config.ini file.

Would you be interested in becoming a member of the KaHyPar organization and in migrating your interface repository to the KaHyPar org?

**Comment by SebastianSchlag** [comment]
I just updated our project [readme](https://github.com/kahypar/kahypar#the-java-interface) to include your interface!

**Comment by romainwallon** [comment]
Hi Sebastian,

Thanks for your reply!

I may miss something, but it seems that this solution does not work.
When I add `quiet_mode=true` to this [config.ini](https://github.com/kahypar/kahypar/files/4952184/config.ini.gz) file, I still get the same kind of output when programmatically executing KaHyPar as when running the following command (with the same ini file):

```bash
./kahypar/application/KaHyPar -h special_instances/star_like_structure.hgr -k 2 -e 0.03 -o cut -m direct -p config.ini
```

Do you have any idea of why there is still this output?

Regarding the migration to KaHyPar organization, I need to ask on my side whether this is possible.
I will get back to you as soon as I have more informations about this.
Thanks for adding the interface to your readme!

Best regards,
Romain

**Comment by SebastianSchlag** [comment]
Sorry about that. Quiet-mode (and its usage) apparently was a bit broken. I just fixed it in https://github.com/kahypar/kahypar/commit/2524001a38de0955c5c5bafdcd112591eed52dda. Now using the `--quiet=1` command line option, or `quiet=1` in the ini config really disables the entire output.

(@larsgottesbueren: As side result, KaHyPar now also allows to set the generic options via ini config.)

**Comment by SebastianSchlag** [comment]
> Regarding the migration to KaHyPar organization, I need to ask on my side whether this is possible.
> I will get back to you as soon as I have more informations about this.
> Thanks for adding the interface to your readme!

Cool! I am looking forward to hearing from you. In any case, thank you very much for making the repository public!

**Comment by romainwallon** [comment]
Thanks! This solution works for me!
I am thus going to close the issue.

I will contact you later about the migration: there are not many people at this time of the year I can reach for getting the information and authorization I need, but I hope I will be able to give you an answer by September.

Best regards,
Romain
