### ISSUE TITLE
Custom target block weights and python interface issue for kahypar 1.1.2

### ISSUE THREAD

**Issue by roguzsel** [kahypar/kahypar#64]
Hi,

I am trying to use the python interface installing it via pip. The version installed via pip is 1.1.1 and it seems to not contain the custom block weights in the context object:

```
[('__init__',
  <bound method PyCapsule.__init__ of <kahypar.Context object at 0x2aaaabf1a030>>),
 ('loadINIconfiguration',
  <bound method PyCapsule.loadINIconfiguration of <kahypar.Context object at 0x2aaaabf1a030>>),
 ('setEpsilon',
  <bound method PyCapsule.setEpsilon of <kahypar.Context object at 0x2aaaabf1a030>>),
 ('setK',
  <bound method PyCapsule.setK of <kahypar.Context object at 0x2aaaabf1a030>>),
 ('setSeed',
  <bound method PyCapsule.setSeed of <kahypar.Context object at 0x2aaaabf1a030>>),
 ('suppressOutput',
  <bound method PyCapsule.suppressOutput of <kahypar.Context object at 0x2aaaabf1a030>>)]
```

I believe this option is added in 1.1.2. If so, do you have any idea why pip cannot install kahypar 1.1.2?
If I run ```pip install --user kahypar``` or ```python3 -m pip install --index-url https://pypi.org/simple/ --no-deps kahypar```, it installs version 1.1.1.
And if I try to enforce 1.1.2 by specifying kahypar==1.1.2, it outputs:
```
Looking in indexes: https://pypi.org/simple/
Collecting kahypar==1.1.2
  ERROR: Could not find a version that satisfies the requirement kahypar==1.1.2 (from versions: 1.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.1.1)
ERROR: No matching distribution found for kahypar==1.1.2
```

It is weird since when I run ```pip search kahypar```, it seems to be aware that 1.1.2 is the latest version and it is there:
```
kahypar (1.1.2)  - Python Inferface for the Karlsruhe Hypergraph Partitioning Framework (KaHyPar)
  INSTALLED: 1.1.1
  LATEST:    1.1.2
```

Any idea what may be wrong and what is going on?
I am using python version 3.7.4.

Thanks!

**Comment by SebastianSchlag** [comment]
Hi,
thanks for reaching out! This seems kind of odd. What OS do you use. The prebuilt pip binaries currently only support macOS and Linux.
Could you try do download and install the corresponding wheel directly from https://files.pythonhosted.org/packages/47/e6/90a8ab519b09bcbd5ee7743520c78840131aada865c9217d1942805e7a6a/kahypar-1.1.2-cp37-cp37m-manylinux2014_x86_64.whl (or https://files.pythonhosted.org/packages/ad/a4/6ef67dd57be2371d6bb35eaafa37f03657d207c5e71736c8c759906371c9/kahypar-1.1.2-cp37-cp37m-macosx_10_9_x86_64.whl in case of macOS)?

Also could you please run pip again using `--verbose`? Maybe the verbose output contains some clues on why this is happening.

Best regards,
Sebastian

**Comment by roguzsel** [comment]
I use linux. When I try to install via wheel (the first link you provided) using ```pip install --verbose --user kahypar-1.1.2-cp37-cp37m-manylinux2014_x86_64.whl```, it gives the following error:

```
ERROR: kahypar-1.1.2-cp37-cp37m-manylinux2014_x86_64.whl is not a supported wheel on this platform.
Exception information:
Traceback (most recent call last):
  File "/global/common/cori_cle7/software/python/3.7-anaconda-2019.10/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 188, in main
    status = self.run(options, args)
  File "/global/common/cori_cle7/software/python/3.7-anaconda-2019.10/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 319, in run
    self.name, wheel_cache
  File "/global/common/cori_cle7/software/python/3.7-anaconda-2019.10/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 281, in populate_requirement_set
    requirement_set.add_requirement(req_to_add)
  File "/global/common/cori_cle7/software/python/3.7-anaconda-2019.10/lib/python3.7/site-packages/pip/_internal/req/req_set.py", line 91, in add_requirement
    wheel.filename
pip._internal.exceptions.InstallationError: kahypar-1.1.2-cp37-cp37m-manylinux2014_x86_64.whl is not a supported wheel on this platform.
```

And here is the verbose output when I run ```pip install kahypar``` and how it skips version 1.1.2 and installs version 1.1.1:

https://pastebin.com/nAcFiFua

I think the line it should be installing is line 69, but it somehow skips that one. My system's suffix seems to be ```cp37-cp37m-manylinux2014_x86_64```, and there is a version of 1.1.2 with exactly that suffix.

**Comment by SebastianSchlag** [comment]
Could you please doublecheck via `pip debug -v` that your system's suffix is indeed `cp37-cp37m-manylinux2014_x86_64` , since only `1.1.1-cp37-cp37m-manylinux2010_x86_64.whl` seems to be valid for your system?

I'm no expert in all of this python package management, but I'll try to come up with a solution. 

In the meantime, you could also try do build the python interface from scratch as described here: https://github.com/kahypar/kahypar#the-python-interface

**Comment by roguzsel** [comment]
The suffix ```cp37-cp37m-manylinux2010_x86_64``` is listed among the compatible tags. My pip version is ```19.2.3```, so that might be the problem.

I tried it on another system with pip version 20.1.1, and now I can install version 1.1.2! But the problem is, when I use ```context.setCustomTargetBlockWeights([2, 5])```, it complains:
```AttributeError: 'kahypar.Context' object has no attribute 'setCustomTargetBlockWeights'```

If I omit that function and use setEpsilon, it just runs fine. Can you confirm the version 1.1.2 actually contains function ```setCustomTargetBlockWeights```?

**Comment by SebastianSchlag** [comment]
Oh, this functionality was indeed not present in version `1.1.2`. I've just updated the python package to `1.1.3`, which now includes individual block weights.

**Comment by roguzsel** [comment]
Now I can see and use it.

Thanks!
