### ISSUE TITLE
Questions about Using the C-Style Interface

### ISSUE THREAD

**Issue by zephyr-jebel** [kahypar/kahypar#75]
After successfully installing KaHyPar and building KaHyPar as a library, I tried to test the source file you provided. However, when I use g++ like 
`g++ -std=c++14 -DNDEBUG -O3 -I/usr/local/include -L/usr/local/lib -L/usr/lib -I/usr/include -lboost_program_options program.cc -o program`
it reports
```program.cc:(.text.startup+0x21): undefined reference to `kahypar_context_new' ```
```program.cc:(.text.startup+0x37): undefined reference to `kahypar_configure_context_from_file'```
```program.cc:(.text.startup+0x107): undefined reference to `kahypar_partition'```
```program.cc:(.text.startup+0x1d5): undefined reference to `kahypar_context_free'```
```collect2: error: ld returned 1 exit status```
I wonder if I have misunderstood the meaning of your example. I will appreciate it if your can help me solve this problem.

**Comment by SebastianSchlag** [comment]
Hi,
thanks for reaching out. I think you are missing the `-lkahypar` parameter in your `g++` call.

**Comment by zephyr-jebel** [comment]
> Hi,
> thanks for reaching out. I think you are missing the `-lkahypar` parameter in your `g++` call.

Thank you, 
but It reports the same error when I add it like this
```g++ -std=c++14 -DNDEBUG -O3 -I/usr/local/include -L/usr/local/lib -lkahypar -L/usr/lib -I/usr/include -lboost_program_options program.cc -o program```
I have checked that `libkahypar.h` do exist in `/usr/local/include` and `libkahypar.so` in `/usr/local/lib`.
Also I can use boost library to compile other source code in g++ call in that path for boost.

**Comment by SebastianSchlag** [comment]
Hm... this seems strange I just tried it again on my local system and everything works as expected. What compiler and OS are you using?

**Comment by zephyr-jebel** [comment]
g++ (Ubuntu 9.3.0-11ubuntu0~18.04.1) 9.3.0
Ubuntu 18.04.5 LTS (GNU/Linux 5.4.0-48-generic x86_64)

**Comment by zephyr-jebel** [comment]
I have just tried to reinstall it, and everything seems to be fine in the picture. But the same error was reported again.
<img width="394" alt="p1" src="https://user-images.githubusercontent.com/52501558/95851188-75e94c80-0d84-11eb-82f5-c906d70405ef.png">

**Comment by SebastianSchlag** [comment]
Did you try do uninstall it first via `make uninstall-kahypar`? Otherwise the `make install.library` might just do nothing.

**Comment by zephyr-jebel** [comment]
> Did you try do uninstall it first via `make uninstall-kahypar`? Otherwise the `make install.library` might just do nothing.

Yes, I did `make uninstall-kahypar`.

**Comment by SebastianSchlag** [comment]
> > Did you try do uninstall it first via `make uninstall-kahypar`? Otherwise the `make install.library` might just do nothing.
> 
> Yes, I did `make uninstall-kahypar`.

I'm sorry, then I'm afraid that I can't help you right now. It seems to be an issue with your linker. @kittobi1992 @larsgottesbueren any ideas what could go wrong here?

**Comment by zephyr-jebel** [comment]
Sincerely thank you for your patient reply!

**Comment by cameton** [comment]
Hello, did you ever manage to find a solution to this? I seem to be having the same issue.
Version Information:
g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Kubuntu 20.04 LTS

There were a number of warnings when building. Could those have something to do with it? 

That said, the build was reported as successful and there seemed to be tests running successfully as well.

**Comment by SebastianSchlag** [comment]
Could you paste the logs produced by cmake and make (maybe even with cmake verbose mode[1])? Maybe this will yield a hint on what is going wrong.


[1] https://bytefreaks.net/programming-2/make-building-with-cmake-verbose

**Comment by larsgottesbueren** [comment]
The warnings shouldn't be an issue. I think they're for some style guide violations in the external whfc library (my bad -.-). I've never worked with the kahypar library interface myself, so absolutely no idea what might be going wrong there.

**Comment by shibizhao** [comment]
@zephyr-jebel  Hi, I have the same question with you. Maybe you can try this command:
`g++ -std=c++14 -DNDEBUG -O3 program.cc -o program -I/usr/local/include -L/usr/local/lib -lkahypar -L/usr/lib -I/usr/include -lboost_program_options`
It works on my ubuntu 18.04.

**Comment by zephyr-jebel** [comment]
> @zephyr-jebel Hi, I have the same question with you. Maybe you can try this command:
> `g++ -std=c++14 -DNDEBUG -O3 program.cc -o program -I/usr/local/include -L/usr/local/lib -lkahypar -L/usr/lib -I/usr/include -lboost_program_options`
> I don't understand it, but it works on my ubuntu 18.04.

It also works on my ubuntu 18.04. Thanks for your help.

**Comment by SebastianSchlag** [comment]
Now, I have to admit that I am a bit confused. This seems to be exactly (minus argument order) the same command that apparently did not work before:

> > Hi,
> > thanks for reaching out. I think you are missing the `-lkahypar` parameter in your `g++` call.
> 
> Thank you,
> but It reports the same error when I add it like this
> `g++ -std=c++14 -DNDEBUG -O3 -I/usr/local/include -L/usr/local/lib -lkahypar -L/usr/lib -I/usr/include -lboost_program_options program.cc -o program`
> I have checked that `libkahypar.h` do exist in `/usr/local/include` and `libkahypar.so` in `/usr/local/lib`.
> Also I can use boost library to compile other source code in g++ call in that path for boost.

Nevertheless, thank you very much @shibizhao for helping out with this issue! 👍
