### ISSUE TITLE
python library interface

### ISSUE THREAD

**Issue by maliabd-al-majid** [kahypar/kahypar#78]
i have just installed kahypar .
and used the same example for python interface.
but i am just asking how to get nodes of each block .
i found that it should be in blockID():

after i used partition :
`kahypar.partition(self.__get_graph(),self.__get_context())`

i just tried to get block id for each node.
```
        for p in self.__get_graph().nodes():

            print(self.__get_graph().blockID(p))
```
please assist and sorry for inconvenient

**Comment by SebastianSchlag** [comment]
Hi Mohamed, 
I just realised that we never closed this issue after I got in touch with you via email. Did you get the python interface working?

**Comment by maliabd-al-majid** [comment]
yeah sorry it was something with my configuration file. 
i would like to ask if there is some limits for number of nodes in partitioning , as whenever i try to partition large number of nodes , i got issue . i mean that it freezes and doesn't show any result.

**Comment by SebastianSchlag** [comment]
A couple of follow up questions:
- How big is the graph you are trying to partition?
- Did you build KaHyPar in release mode? The debug mode contains several fairly expensive assertions and is infeasible for large instances
- Does the hypergraph contain hyperedges in which a vertex appears more than once? This is not supported by KaHyPar and may result in an infinite loop during coarsening.
-  Could you run KaHyPar with the `--verbose=1` option? This way you get a progress bar during coarsening and local search. That way we could identify the part of the algorithm that is slow.

**Comment by Sijibomi-olu** [comment]
Hello please how do you install kahypar on python windows
