### ISSUE TITLE
have cmake flags to disable including Python binding and application in CMakeFiles

### ISSUE THREAD

**Issue by Roger-luo** [kahypar/kahypar#85]
I think this will make building the share lib for other languages much easier when Python/pybind11 is not needed

I currently have to use a patch here: https://github.com/JuliaPackaging/Yggdrasil/pull/3111/files#diff-04b01b818aba662637ce0b4bb535b08e4d9944ac0bad644cfcb1220b6991974dR37
because this cause cmake complains the default python is not 32-bit on some platforms (not sure if you want to support 32-bit or not tho)

**Comment by SebastianSchlag** [comment]
Yes, I totally agree. I've added a cmake flag in https://github.com/kahypar/kahypar/pull/89.
