### ISSUE TITLE
Have a CMake flag to disable tests

### ISSUE THREAD

**Issue by giordano** [kahypar/kahypar#87]
[`CTest`](https://cmake.org/cmake/help/latest/module/CTest.html) defines an option, `BUILD_TESTING`, to let the user decide whether to build tests or not.  It'd be good to use it, to avoid building tests when not necessary, for example when cross-compiling without having an emulator to actually run the tests.  This is on the same vein as #85.

For what is worth, I can successfully cross-compile the library for Windows using [BinaryBuilder](https://binarybuilder.org/) after applying #86, manually disabling all tests (it took a while....) and working around the errors reported in https://github.com/kahypar/kahypar/issues/83#issuecomment-851038929.

**Comment by SebastianSchlag** [comment]
> For what is worth, I can successfully cross-compile the library for Windows using [BinaryBuilder](https://binarybuilder.org/) after applying #86, manually disabling all tests (it took a while....) and working around the errors reported in [#83 (comment)](https://github.com/kahypar/kahypar/issues/83#issuecomment-851038929).

What exactly did you do to work around the issues in https://github.com/kahypar/kahypar/issues/83#issuecomment-851038929? Would you mind submitting a PR with those fixes?

**Comment by SebastianSchlag** [comment]
With https://github.com/kahypar/kahypar/pull/88, we now have the option to disable the tests.

**Comment by giordano** [comment]
Cool, thanks!
