### ISSUE TITLE
Installing kayhpar

### ISSUE THREAD

**Issue by Sijibomi-olu** [kahypar/kahypar#92]
I am unable to install kahypar using pip install, please help
![Screenshot (759)](https://user-images.githubusercontent.com/62013721/123505894-62072180-d659-11eb-80bc-46e74799d71f.png)

**Comment by SebastianSchlag** [comment]
Thanks for reaching out.

What python version are you using?

**Comment by Sijibomi-olu** [comment]
Python 3.8.10

**Comment by AmirHmZz** [comment]
I have the exact same problem using **Python 3.9.1** on **Windows 10**

**Comment by AmirHmZz** [comment]
It seems you don't provide any wheels for windows... 
That's not good.

**Comment by SebastianSchlag** [comment]
Yes, that's correct. Direct Windows support is currently limited. However, I know that several people could built KaHyPar successfully using the [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10).

**Comment by AmirHmZz** [comment]
So why you mention this on project description : 

> A 64-bit operating system. Linux, Mac OS X and Windows are currently supported.

Any way if anyone succeed with building python interface for windows, I'll be happy to know how!

**Comment by SebastianSchlag** [comment]
The project is constantly evolving... Also, I know that several people successfully built it on Windows (and/or its Linux subsystem).
