### ISSUE TITLE
Fail building on windows 10!

### ISSUE THREAD

**Issue by AmirHmZz** [kahypar/kahypar#93]
While I'm building on windows I'm getting this error :
```
-- Found PythonInterp: C:/Program Files/Python39/python.exe (found version "3.9.1")
CMake Error at C:/Program Files/CMake/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Boost (missing: Boost_INCLUDE_DIR program_options) (Required
  is at least version "1.69")
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.20/Modules/FindBoost.cmake:2345 (find_package_handle_standard_args)
  CMakeLists.txt:174 (find_package)
```

**Comment by SebastianSchlag** [comment]
It seems that `cmake` didn't find boost. Did you install the boost dependency?

**Comment by AmirHmZz** [comment]
Thanks, the problem was with boost library, I've fixed it but now I'm struggling with another issue : 
It seems some part of your project is using C++17 new features. Is there any of Visual studio versions supporting C++17 ? 
I've done everything and the last thing that is left is building final python interface ( kahypar-python ) which a project in a cmake built solution.

**Comment by SebastianSchlag** [comment]
I don't know about much about MSVC compilers, but given the fact that other users have successfully built KaHyPar on Windows, I guess there is one that supports C++17.

**Comment by AmirHmZz** [comment]
I've tried a lot but I failed... , Anyway would you please provide some standalone executables for windows ?

**Comment by SebastianSchlag** [comment]
I think most of us don't have access to windows machines. Did you try the [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10)?

If I remember correctly, @kittobi1992 was able to compile KaHyPar using the subsystem. @kittobi1992  please correct me if I am wrong.
