### ISSUE TITLE
Context initialization

### ISSUE THREAD

**Issue by jm62300** [kahypar/kahypar#94]
Dear kahypar developer,
I try to integrate kahypar in d4 (http://www.cril.univ-artois.fr/kc/d4.html) to replace which is not open source.
However, kahypar requieres the use of external file for initializing a context which is not really optimal for me.
Can we initialize a context without a configuration file?

BTW, there are a lot of configuration files and I do not which one is more related to my application.
The hypergraph I consider are not that big, and I can call kahypar several times on such small hypergraph.
Actually, I would like to know if it is possible to have different level of optimization (ex, level 1 speed is mandatory, level 2 quality is mandatory, ...).
Best regards,
JM

**Comment by SebastianSchlag** [comment]
Dear JM, thanks for reaching out.
Unfortunately, the interfaces don't support initialization without config yet. However, you should be good with hard-coding either [km1_kKaHyPar_sea20.ini](https://github.com/kahypar/kahypar/blob/master/config/km1_kKaHyPar_sea20.ini) for connectivity optimization or [cut_kKaHyPar_sea20.ini](https://github.com/kahypar/kahypar/blob/master/config/cut_kKaHyPar_sea20.ini) for cut-net optimzation.

KaHyPar doesn't really offer different speed/quality presets. Instead it aims to provide the best partitioning quality at reasonable running times. If your hypergraphs are small, then partitioning time shouldn't be an issue.

**Comment by jm62300** [comment]
Thx for your answers.
JM

**Comment by SebastianSchlag** [comment]
You're welcome.
Feel free to reach out anytime if you encounter more issues during your integration.
