### ISSUE TITLE
macOS:Reason: image not found

### ISSUE THREAD

**Issue by YwY2311** [kahypar/kahypar#95]
ImportError: dlopen(/opt/anaconda3/lib/python3.8/site-packages/kahypar.cpython-38-darwin.so, 2): Library not loaded: /usr/local/opt/boost/lib/libboost_program_options-mt.dylib
  Referenced from: /opt/anaconda3/lib/python3.8/site-packages/kahypar.cpython-38-darwin.so
  Reason: image not found
how to solve it?

**Comment by SebastianSchlag** [comment]
This looks like you don't have installed the boost library correctly (or that it is not in your path). Could you please verify that?

**Comment by nina23bom** [comment]
> 
I have the same issue. 

Could you please be more specific? What is the purpose to have boost library installed, and how should I do it? 
I use macOS 10.15.6 
and Python 3.8.3

Thanks in advance!

**Comment by SebastianSchlag** [comment]
Hey @nina23bom, I commented in https://github.com/kahypar/kahypar/issues/106.

**Comment by SebastianSchlag** [comment]
>  What is the purpose to have boost library installed

KaHyPar uses boost's [program options](https://www.boost.org/doc/libs/1_64_0/doc/html/program_options.html) library for parsing the all the command line arguments and ini config files.
