### ISSUE TITLE
Hide Kahypar Result Message

### ISSUE THREAD

**Issue by jiyoonlim123** [kahypar/kahypar#97]
When I run experiments, usually kahypar's result message is unneeded.
Is there any method to hide the below result message with the python interface?
![image](https://user-images.githubusercontent.com/86942129/133872883-4b1178ad-e144-4ef9-a3f8-f5353ce55dac.png)

**Comment by SebastianSchlag** [comment]
Hi @jiyoonlim123, thanks for reaching out.
You can suppress KaHyPar's output using the `--quiet=1` command line option, or `quiet=1` in the ini config file.

**Comment by jiyoonlim123** [comment]
Thanks for the reply. It works.
